create or replace PROCEDURE  EXEC_QUARTER is
    VL_ID         NUMBER;
    DT_HR_INICIO  DATE;
    WS_ID_ALERT   NUMBER;
    WS_QTDE_FILA  NUMBER := 0;
    ANOMES_INICIO VARCHAR(6);
    ANOMES_FIM    VARCHAR(6);

    WS_FILA       EXCEPTION;
begin

    DT_HR_INICIO := SYSDATE;
    WS_ID_ALERT  := NULL;
    ANOMES_INICIO := TO_CHAR(ADD_MONTHS(SYSDATE,-1),'YYYYMM');
    ANOMES_FIM    :=TO_CHAR(SYSDATE,'YYYYMM');
          
    --DWU.SCH.ALERT_ONLINE(WS_ID_ALERT, 'QUARTER', DT_HR_INICIO, NULL,NULL,'ATUALIZANDO','', 'REGISTRO', 'N');
   
    /* -- APENAS SE O CLIENTE USAR INTEGRADOR. SE NÃO, REMOVER ESSA PARTE
    
    SELECT COUNT(*) INTO WS_QTDE_FILA FROM ETL_FILA WHERE STATUS IN ('A','R');
    
    IF WS_QTDE_FILA >= 1 THEN
    RAISE WS_FILA;
    END IF;
    */ -- APENAS SE O CLIENTE USAR INTEGRADOR. SE NÃO, REMOVER ESSA PARTE

   /* -- DELETE VM_ACESSOS_BI WHERE DT_EMISSAO >=TRUNC(SYSDATE-10);
   INSERT INTO VM_ACESSOS_BI SELECT * FROM V1_ACESSOS_BI WHERE DT_EMISSAO >=TRUNC(SYSDATE-10); 
   COMMIT;--*/
    
    NULL;
    /*
    DELETE FROM VM_ACESSOS_BI WHERE ANOMES_EMISSAO = ANOMES_FIM;
    INSERT INTO VM_ACESSOS_BI SELECT * FROM V1_ACESSOS_BI WHERE ANOMES_EMISSAO = ANOMES_FIM;
    COMMIT; 
    */
    
   --DWU.SCH.ALERT_ONLINE(WS_ID_ALERT, 'QUARTER', DT_HR_INICIO, SYSDATE,NULL,'FINALIZADO','', 'REGISTRO', 'N'); 
    
EXCEPTION 
    /* -- APENAS SE O CLIENTE USAR INTEGRADOR. SE NÃO, REMOVER ESSA PARTE
    WHEN WS_FILA THEN
    DWU.SCH.ALERT_ONLINE(WS_ID_ALERT, 'QUARTER', DT_HR_INICIO, SYSDATE,NULL,'ERRO','AÇÕES ACUMULADAS NA ETL_FILA', 'ENVIO', 'N'); 
    */ -- APENAS SE O CLIENTE USAR INTEGRADOR. SE NÃO, REMOVER ESSA PARTE
    
    WHEN OTHERS THEN
    DWU.SCH.ALERT_ONLINE(WS_ID_ALERT, 'QUARTER', DT_HR_INICIO, SYSDATE,NULL,'ERRO', DBMS_UTILITY.FORMAT_ERROR_STACK||'-'||DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, 'ENVIO', 'N');                  
end;