create or replace PROCEDURE EXEC_DAY is

VL_ID NUMBER;
DT_HR_INICIO DATE;
WS_ID_ALERT   NUMBER;

begin

DT_HR_INICIO := SYSDATE;
WS_ID_ALERT  := NULL;
    
  --  DWU.SCH.ALERT_ONLINE(WS_ID_ALERT, 'DAY', DT_HR_INICIO, NULL,NULL,'ATUALIZANDO','', 'REGISTRO', 'N');
    
    IF(TO_CHAR(SYSDATE,'DD') IN ('01','05','10',',15','20','25','30')) THEN
       ATU_ESTRUTURA_BANCO;
    END IF;
    
    LIMPA_TABLESPACE;

 --   DWU.SCH.ALERT_ONLINE(WS_ID_ALERT, 'DAY', DT_HR_INICIO, SYSDATE,NULL,'FINALIZADO','', 'REGISTRO', 'N'); 
    
    EXCEPTION WHEN OTHERS THEN
    DWU.SCH.ALERT_ONLINE(WS_ID_ALERT, 'DAY', DT_HR_INICIO, SYSDATE,NULL,'ERRO', DBMS_UTILITY.FORMAT_ERROR_STACK||'-'||DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, 'ENVIO', 'N');                  
END;