-- 
-- update atualiza somente os campos descricao, nome, ordem e permissao (não pode alterar o conteúdo, cada cliente tem sua parametrização própria)
begin
    --
	-- Permissões de acesso a variável 
	--   - TTT 	  Visualizacao (TODOS)      Alteração (TODOS)      Exclusão (TODOS) 
	--   - TTN    Visualizacao (TODOS)      Alteração (TODOS)      Exclusão (NINGUEM) 
	--   - TNN    Visualizacao (TODOS)      Alteração (NINGUEM)    Exclusão (NINGUEM)  
	--   - NNN    Visualizacao (NINGUEM)    Alteração (NINGUEM)    Exclusão (NINGUEM)  
	--   - TUN    Visualizacao (TODOS)      Alteração (UPQUERY)    Exclusão (NINGUEM)  
	--   - UUN    Visualizacao (UPQUERY)    Alteração (UPQUERY)    Exclusão (NINGUEM)  
    --
    -- 1.5.6
    delete var_conteudo where variavel in ('COM_USER', 'COM_PASS'); -- Exclusao - variável descontinuada 
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'CLIENTE' variavel, '' conteudo, 'Código do cliente Upquery.' descricao, 'TUN' permissao, 'Cód. Cliente' nome, 1 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'APPCODE' variavel, '' conteudo, 'Código para acesso via aplicativo.' descricao, 'TUN' permissao, 'Cód. Aplicativo' nome, 2 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'TEMPO_EXPIRA_SESSAO' variavel, '0' conteudo, 'Tempo em minutos para encerramento de sess&otilde;es inativas.'||chr(10)||'Informar 0 para n&atilde;o expirar sess&atilde;o.' descricao, 'TTN' permissao, 'Tempo Expira Sessão' nome, 3 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'TEMPO_EXPIRA_SENHA' variavel, '0' conteudo, 'Informar o tempo em dias para expira&ccedil;&atilde;o da senha dos usuários.'||chr(10)||'Informar 0 para que o sistema não faça o controle de expiração de senha.' descricao, 'TTN' permissao, 'Tempo Expira Senha' nome, 4 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'TIPO_EXPIRA_SENHA' variavel, 'T' conteudo, 'Informar a forma de cadastro da nova senha após a expiração.'||chr(10)||'E - Cadastro via emails enviados para o usuário.'||chr(10)||'T - Tela de cadastro de senha aberta após o login.'||chr(10)||'Se estiver com qualquer conteudo que não seja E ou T o sistema assumirar E como padrão.' descricao, 'TTN' permissao, 'Tipo Expira Senha' nome, 5 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'TEMPO_EXPIRA_EMAIL' variavel, '0' conteudo, 'Informar o tempo em dias para expira&ccedil;&atilde;o da &uacute;ltima valida&ccedil;&atilde;o de identidade do usu&aacute;rio através do e-mail.'||chr(10)||'Informar 0 para n&atilde;o expirar a valida&ccedil;&atilde;o de identidade do usu&aacute;rio, com isso o sistema solicitar&aacute; a valida&ccedil;&atilde;o somente para novos usu&aacute;rios, ou quando houver altera&ccedil;&atilde;o do email do usu&aacute;rio.' descricao, 'TTN' permissao, 'Tempo Expira E-mail' nome, 6 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'FORMATO_EXCEL' variavel, 'HTML' conteudo, 'Formato do conte&uacute;do do arquivo gerado, preencher com:'||chr(10)||'XLSX - Formato Excel com extensão .xlsx (sem formata&ccedil;&atilde;o).'||chr(10)||'HTML - Formato HTML com extensão .xls (com formata&ccedil;&atilde;o).'||chr(10)||'Para qualquer outro conte&uacute;do o sistema assume formato HTML' descricao, 'TTN' permissao, 'Formato Exporta Excel' nome, 7 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'BLOQ_QUARTER' variavel, 'N' conteudo, 'Preecher com S para pausar a execução do Job Quarter.' descricao, 'TTN' permissao, 'Travar Rotina Quarter' nome, 8 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'HR_AUTOUPDATE_BAIXA' variavel, '19' conteudo, 'Horário da baixa das últimas atualizações de sistema, a aplicação das atualizações baixadas é realizada somente no primeiro horário do dia seguinte a baixa.' descricao, 'UUN' permissao, 'Horário Update Sistema' nome, 9 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'EXPIRA_REL' variavel, '0' conteudo, 'Tempo limite de execução dos relatórios, o relatório é encerrado automaticamente após esse tempo.'||chr(10)||'Informar tempo em minutos.' descricao, 'UUN' permissao, 'Tempo Limite Relatório' nome, 10 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'DATA_ATUAL' variavel, '01/jan/2022' conteudo, 'Data atual do sistema.' descricao, 'UUN' permissao, 'Data Atual' nome, 30 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'DIA_REFERENCIA' variavel, '01/jan/2022' conteudo, 'Não utilizado no BI, verificar se é utilizado em carga de dados' descricao, 'NNN' permissao, 'Dia Referência' nome, 31 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'DIA_TROCA' variavel, '01/jan/2022' conteudo, 'Utilizado pelo JOB_QUARTER para controle da troca de dia.'||chr(10)||'Atualizado automaticamente na primeira execução do dia do JOB_QUARTER.' descricao, 'UUN' permissao, 'Dia Troca' nome, 32 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'CORREIO' variavel, '' conteudo, 'Servidor de email utilizado para envio de emails padrões do sistema.' descricao, 'UUN' permissao, 'Serviço e-mail' nome, 40 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'CORREIO_PORT' variavel, '' conteudo, 'Porta do servidor de email utilizado para envio de emails padrões do sistema.' descricao, 'UUN' permissao, 'Porta e-mail' nome, 41 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'CORREIO_USER' variavel, '' conteudo, 'Usuário de email utilizado para envio de emails padrões do sistema.' descricao, 'UUN' permissao, 'Usuário e-mail' nome, 42 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'CORREIO_PASS' variavel, '' conteudo, 'Senha do usuário de email utilizado para envio de emails padrões do sistema.' descricao, 'UUN' permissao, 'Senha e-mail' nome, 43 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'DOMINIO_REG' variavel, 'update.upquery.com' conteudo, 'Domínio do servidor Upquery (cadastro obrigatório).' descricao, 'UUN' permissao, 'DOMINIO_REG' nome, 60 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'REQUEST_REG' variavel, 'update.upquery.com:7776' conteudo, '' descricao, 'UUN' permissao, 'REQUEST_REG' nome, 61 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'ORACLE_VERSION' variavel, '11' conteudo, 'Versão do Oracle, deve ser informado somente o número da versão, não pode ser informado letras ou qualquer outro caracter.'||chr(10)||'Para versão 19c, por exemplo, deve ser informado somente o número 19.' descricao, 'UUN' permissao, 'Versão Oracle' nome, 62 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'CHARSET' variavel, 'AL32UTF8' conteudo, 'Informar Character Set utilizado no banco de dados. ' descricao, 'UUN' permissao, 'CHARSET' nome, 63 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'LANG' variavel, 'S' conteudo, 'Ativa controle de idiomas diferentes do idioma padrão do sistema (Português Brasil).'||chr(10)||'Informar:'||chr(10)||'S - Para possibilitar a utilização de idiomas diferentes do idioma padrão do sistema.'||chr(10)||'Qualquer outro valor para utlização somente do idioma padrão do sistema. ' descricao, 'UUN' permissao, 'Controle de Idioma' nome, 64 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'LANG_DEFAULT' variavel, 'PORTUGUESE' conteudo, 'Linguagem padrão do sistema, informar: PORTUGUESE, ENGLISH, SPANISH, ITALIAN ou GERMAN.' descricao, 'UUN' permissao, 'Idioma Padrão' nome, 65 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'LANG_SYS' variavel, 'PORTUGUESE' conteudo, 'Linguagem nativa do BI (PORTUGUESE), não deve ser alterado.' descricao, 'UNN' permissao, 'Idioma Nativo' nome, 65 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'LANG_DATE' variavel, 'PORTUGUESE' conteudo, 'Linguagem de data padrão do banco de dados (NLS_DATE_LANGUAGE).' descricao, 'UUN' permissao, 'Linguagem Data Oracle' nome, 66 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'POINT' variavel, ',.' conteudo, 'Formato númerico utilizado pelo banco de dados(NLS_NUMERIC_CHARACTERS).'||chr(10)||'Informar: ,. (virgula para casas de milhar e ponto para casas decimal).'||chr(10)||'ATENÇÃO é o formato utilizadodo banco de dados não o formato utilizado nas telas do sistema' descricao, 'UUN' permissao, 'Máscara Numerica Oracle' nome, 67 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'ATIVAR_CHAT' variavel, 'N' conteudo, 'Ativa ou desativa o CHAT do BI.'||chr(10)||'S - Ativa o chat.'||chr(10)||'N - Não ativa o chat.'||chr(10)||'Se o campo estiver com qualquer outro valor diferente de S, o CHAT não será ativado.' descricao, 'UUN' permissao, 'Ativar Chat' nome, 70 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'GPU' variavel, 'S' conteudo, 'Ativa a aceleração de vídeo 3D (GPU). Melhora a qualidade de algumas animações CSS, porém pode deixar algumas animações mais lentas ou utilizar mais memória em dispositivos móveis.' descricao, 'UUN' permissao, 'Aceleração de Vídeo' nome, 90 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'PROGRAM' variavel, 'httpd.worker@oraserver (TNS V1-V3)' conteudo, 'Utilizado na consulta de processos do banco de dados.' descricao, 'NNN' permissao, 'PROGRAM' nome, 91 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'LOCK_SYS' variavel, 'OFF' conteudo, 'Bloqueio temporário do sistema para possíveis manutenções.'||chr(10)||'OFF - Desbloqueia o sistema'||chr(10)||'Qualquer outro valor, bloqueia o sistema para novos acessos e sessões ativas em até 60 segundos.'||chr(10)||'' descricao, 'UUN' permissao, 'Bloqueio Sistema' nome, 100 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'LOGO' variavel, '' conteudo, 'Descontinuado a partir da versão 1.5.6' descricao, 'NNN' permissao, 'LOGO' nome, 9999 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'ID_CONFIG' variavel, '' conteudo, 'Descontinuado (excluir' descricao, 'NNN' permissao, 'ID_CONFIG' nome, 9999 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'URL_GIFS' variavel, '../../util/gifs/' conteudo, 'Descontinuado (excluir)' descricao, 'NNN' permissao, 'URL_GIFS' nome, 9999 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'URL_CHARTS' variavel, '../../util/charts/' conteudo, 'Descontinuado (excluir)' descricao, 'NNN' permissao, 'URL_CHARTS' nome, 9999 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'ALTER_USER' variavel, '' conteudo, 'Descontinuado a partir da versão 1.5.5' descricao, 'NNN' permissao, 'ALTER_USER' nome, 9999 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'MACHINE' variavel, 'EMPRESA' conteudo, 'Descontinuado (excluir)' descricao, 'NNN' permissao, 'MACHINE' nome, 9999 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'URL_FILES' variavel, '../../util/' conteudo, 'Descontinuado (excluir)' descricao, 'NNN' permissao, 'URL_FILES' nome, 9999 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);    
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'ULTIMA_LIMPEZA_LOG' variavel, '' conteudo, 'Data a execução da última limpeza de logs do sistema' descricao, 'NNN' permissao, 'Última Limpeza Logs' nome, 9999 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);    
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'USAR_DBA_DDL_LOCKS'   variavel, 'S'  conteudo, 'Usar tabela dba_ddl_locks para identificar os packotes utilizados pelas sessões. Necessário parametrizar como N para clientes com tempo de select muito lendo para essa tabela.'||chr(10)||'Informar:'||chr(10)||'N - Para não utilizar essa tabela, o sistema não conseguirá matar sessões no momento do auto-update do sistema.'||chr(10)||'S ou branco - Para utilizar a tabela.'  descricao,    'UUN' permissao, 'Usar DBA_DDL_LOCKS' nome, 102 ordem from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);    
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'URL_CLIENTE'       variavel, 102 ordem, 'URL CLIENTE'    nome, 'UUN' permissao, ''  conteudo, 'URL do Cliente utilizado para acesso do TvConex,processo de envio de report por email. Exemplo para cadastro: exemplo.upquery.com/cliente' descricao from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome      = t2.nome, t1.ordem     = t2.ordem, t1.permissao = t2.permissao when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'URL_AUTOUPDATE'    variavel, 103 ordem, 'URL AutoUpdate' nome, 'UUN' permissao, ''  conteudo, 'URL utilizada na atualização de versões do sistema (AutoUpdate).'  descricao from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);        
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'URL_UPDATE'        variavel, 104 ordem, 'URL Update UPQ' nome, 'UUN' permissao, ''  conteudo, 'URL utilizada integrações dos logs de monitoramento.'  descricao  from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);        
    -- 1.5.7
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'OWNER_TABLE_DATA'  variavel, 105 ordem, 'Owner tabelas dados'    nome, 'UUN' permissao, NULL conteudo, 'Owner das tabelas de dados do cliente, se não for preenchido o sistema assumirá o DWU como owner.'  descricao from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);    
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'OWNER_BI'          variavel, 106 ordem, 'Owner sistema BI'       nome, 'UUN' permissao, NULL conteudo, 'Owner dos objetos de sistema, se não for preenchido o sistema assumirá o DWU como owner.'  descricao from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);    	
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'AVISO_MOSTRAR'     variavel, 107 ordem, 'Mostrar Tela Aviso'     nome, 'UUN' permissao, 'S'  conteudo, 'Define se a tela de avisos deve ou não ser exibida na abertura do sistema. Preencher com S ou N, se estiver em branco ou com qualquer outro valor diferente de S e N, o sistema assumirá S como padrão.'  descricao from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);    	    
    -- merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'LIMIT_DOC_BRO'     variavel, 999 ordem, 'Limite Arquivo Browser' nome, 'TTN' permissao, ''   conteudo, 'Define um tamanho limite em KB para o upload dos arquivos do browser' descricao from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);    
    -- Servico de email 
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'COM_ATIVO'      variavel, 'Report - Ativo'      nome, 'UUN' permissao, 120 ordem, 'N' conteudo, 'Ativa ou desativa o processo de envio de report/tela por email, Informar S para ativar ou N para desativar.' descricao                                            from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'COM_TIPO_ENVIO' variavel, 'Report - Tipo Envio' nome, 'UUN' permissao, 121 ordem, 'R' conteudo, 'Forma/tipo de envio do email.'||chr(10)||'L - Envio local através de serviço instalado no servidor.'||chr(10)||'R -Remoto através do servidor Upquery' descricao  from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'COM_END'        variavel, 'Report - URL BI'     nome, 'UUN' permissao, 122 ordem, ''  conteudo, 'URL raiz do BI utilizado para acesso externo pelo processo de envio de report por email. Exemplo: teste.upquery.com/teste' descricao                              from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'COM_KEY'        variavel, 'Report - Chave'      nome, 'UUN' permissao, 123 ordem, ''  conteudo, 'Chave (api-key) de configuração do serviço de envio de email no servidor REMOTO.'||chr(10)||'Necessário somente para tipo de envio R (remoto).' descricao         from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'COM_SERVICO'    variavel, 'Report - Servico'    nome, 'UUN' permissao, 124 ordem, ''  conteudo, 'Endereço do servidor/serviço de email utilizado para envio dos emails de report.'||chr(10)||'Necessário somente para tipo de envio L (local).' descricao          from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'COM_PORTA'      variavel, 'Report - Porta'      nome, 'UUN' permissao, 125 ordem, ''  conteudo, 'Porta do servidor/serviço de email utilizado para envio dos emails de report.'||chr(10)||'Necessário somente para tipo de envio L (local).' descricao             from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'COM_USUARIO'    variavel, 'Report - Usuario'    nome, 'UUN' permissao, 126 ordem, ''  conteudo, 'Usuário do serviço de email utilizado para envio dos email de report.'||chr(10)||'Necessário somente para tipo de envio L (local).' descricao                     from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);    
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'COM_SENHA'      variavel, 'Report - Senha'      nome, 'UUN' permissao, 127 ordem, ''  conteudo, 'Senha do usuário do servico de email utilizado para envio dos email de report.'||chr(10)||'Necessário somente para tipo de envio L (local).' descricao            from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);    
    --
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'CONF_ACESSO_EMAIL' variavel, 'Confirmação Acesso E-mail' nome, 'UUN' permissao, 7 ordem, 'S' conteudo, 'Solicitar confirmação de identificação de acesso por e-mail. Informar:'||chr(10)||'S - para solicitar confirmação de acesso por email.'||chr(10)||'N - para não solicitar confirmação.' descricao from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);        
    --
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'COUNT_MENU' variavel, 'Numerar Menu' nome, 'TTN' permissao, 888 ordem, 'N' conteudo, 'Numerar menu' descricao from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);        
    --
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'CONV_AGRUP_REL' variavel, 'Converter Agrupador Relat&oacute;rio'  nome, 'UUN' permissao, 777 ordem, 'S'  conteudo, 'Ativar o caracter especial e forçar as colunas agrupadoras a serem do tipo TEXTO, para que consigam aceitar zeros a esquerda para cadastros de códigos por exemplo. Defina S para converter e N para não. Para manter o default do sistema mantenha S.' descricao  from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);    
    --
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'LOG_EXEC' variavel, 'Log Execução'  nome, 'UUN' permissao, 130 ordem, 'N'  conteudo, 'Gerar log de execução de objetos. Preencher com:'||chr(10)||'S - Gera e mantém os logs.'||chr(10)||'D - Gera o log mas exclui na finalização do objeto, mantendo somente os logs de objetos não finalizados corretamente.'||chr(10)||'N ou qualquer outro conteúdo - Não gera log.' descricao  from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);    
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'TIPO_AMBIENTE' variavel, 'Tipo Ambiente'  nome, 'NNN' permissao, 999 ordem, 'PRODUCAO'  conteudo, 'Tipo de ambiente do sistema:'||chr(10)||'PRODUCAO    - Ambiente de produção.'||chr(10)||'HOMOLOGACAO - Ambiente de homologação.'||chr(10)||'DESENV      - Ambiente de desenvolvimento.' descricao  from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);    
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'SERVIDOR_ETL'  variavel, 'Servidor do Serviço ETL'  nome, 'UUN' permissao, 131 ordem, ''  conteudo, 'Informar Host e porta do serviço de ETL. Exemplo: 192.123.123.123:5001' descricao  from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);    
    --        
    merge into VAR_CONTEUDO t1 using (select 'DWU' usuario, 'BROWSER_INPUT_HTML' variavel, 'Edição HTML Browser'  nome, 'UUN' permissao, 131 ordem, 'N'  conteudo, 'Permite a criação de campos com tipo de input TEXTO HTML. Preencher com S ou N.' descricao  from dual ) t2  on (t1.variavel = t2.variavel )  when matched then update set t1.descricao = t2.descricao, t1.nome = t2.nome, t1.ordem = t2.ordem, t1.permissao = t2.permissao  when not matched then insert (usuario, variavel, data, conteudo, descricao, nome, ordem, permissao) values (t2.usuario, t2.variavel, sysdate, t2.conteudo, t2.descricao, t2.nome, t2.ordem, t2.permissao);        
    --
    commit; 
    --
end; 
