BEGIN
--
delete from BI_CONSTANTES_BKP;
insert into BI_CONSTANTES_BKP (select * from BI_CONSTANTES);
delete from BI_CONSTANTES;
--
Insert into DWU.BI_CONSTANTES values ('TR_LO_ES','ATENÇÃO !\nSua senha de acesso expirou!\n\nEnviamos um e-mail para o endereço :001 com instruções para alteração da sua senha.','ATENÇÃO !\nSua senha de acesso expirou!\n\nEnviamos um e-mail para o endereço :001 com instruções para alteração da sua senha.');
Insert into DWU.BI_CONSTANTES values ('TR_LO_ET','ATENÇÃO !\nSua senha de acesso expirou!\n\nNa próxima tela aberta pelo sistema informe uma nova senha de acesso.','ATENÇÃO !\nSua senha de acesso expirou!\n\nNa próxima tela aberta pelo sistema informe uma nova senha de acesso.');
Insert into DWU.BI_CONSTANTES values ('TR_CE_CS','A criação da uma NOVA CONSULTA irá excluir a consulta atual ainda não salva, deseja continuar?','A criação da uma NOVA CONSULTA irá excluir a consulta atual ainda não salva, deseja continuar?');
Insert into DWU.BI_CONSTANTES values ('TR_ER_CR','Erro tentando criar objeto.','Erro tentando criar objeto.');
Insert into DWU.BI_CONSTANTES values ('TR_ER_CS','Consulta salva com sucesso.','Consulta salva com sucesso.');
Insert into DWU.BI_CONSTANTES values ('TR_QR_IN','Objeto com a query inválida!','Objeto com a query inválida!');
Insert into DWU.BI_CONSTANTES values ('TR_VL_NL','Coluna selecionada precisa ser de valor!','Coluna selecionada precisa ser de valor!');
Insert into DWU.BI_CONSTANTES values ('TR_SS','Deseja encerrar a sessão?','Deseja encerrar a sessão?');
Insert into DWU.BI_CONSTANTES values ('TR_PR','Processo já esta executando!','Processo já esta executando!');
Insert into DWU.BI_CONSTANTES values ('TR_CS_MA','MAIOR QUE','MAIOR QUE');
Insert into DWU.BI_CONSTANTES values ('TR_CS_ME','MENOR QUE','MENOR QUE');
Insert into DWU.BI_CONSTANTES values ('TR_CS_AI','MAIOR OU IGUAL A','MAIOR OU IGUAL');
Insert into DWU.BI_CONSTANTES values ('TR_CS_EI','MENOR OU IGUAL A','MENOR OU IGUAL');
Insert into DWU.BI_CONSTANTES values ('TR_CS_SE','SEMELHANTE A(LIKE)','SEMELHANTE A(LIKE)');
Insert into DWU.BI_CONSTANTES values ('TR_CS_NS','DIFERENTE(NOT LIKE) DE','DIFERENTE(NOT LIKE) DE');
Insert into DWU.BI_CONSTANTES values ('TR_OFF','Sem conexão!','Sem conexão!');
Insert into DWU.BI_CONSTANTES values ('TR_AD','Adicionado com sucesso!','Adicionado com sucesso!');
Insert into DWU.BI_CONSTANTES values ('TR_TC','Favor preencher todos os campos corretamente!','Favor preencher todos os campos corretamente!');
Insert into DWU.BI_CONSTANTES values ('TR_CR','Criado com sucesso!','Criado com sucesso!');
Insert into DWU.BI_CONSTANTES values ('TR_AL','Alterado com sucesso!','Alterado com sucesso!');
Insert into DWU.BI_CONSTANTES values ('TR_EX','Excluido com sucesso!','Excluido com sucesso!');
Insert into DWU.BI_CONSTANTES values ('TR_ER','Erro ao adicionar!','Erro ao adicionar!');
Insert into DWU.BI_CONSTANTES values ('TR_DP','Já cadastrado!','Já cadastrado!');
Insert into DWU.BI_CONSTANTES values ('TR_ID','Id já utilizado!','Id já utilizado!');
Insert into DWU.BI_CONSTANTES values ('TR_ES','Escolha um valor!','Escolha um valor!');
Insert into DWU.BI_CONSTANTES values ('TR_PS','As senhas digitadas são diferentes!','As senhas digitadas são diferentes!');
Insert into DWU.BI_CONSTANTES values ('TR_BL','Texto não pode estar e branco!','Texto não pode estar e branco!');
Insert into DWU.BI_CONSTANTES values ('TR_CI','Valor inválido, apenas letras, números, underscore e espaço são permitidos!','Valor inválido, apenas letras, números, underscore e espaço são permitidos!');
Insert into DWU.BI_CONSTANTES values ('TR_VI','Valor inválido, apenas letras, números e underscore são permitidos!','Valor inválido, apenas letras, números e underscore são permitidos!');
Insert into DWU.BI_CONSTANTES values ('TR_CM','Tem certeza que gostaria de executar?','Tem certeza que gostaria de executar?');
Insert into DWU.BI_CONSTANTES values ('TR_CE','Tem certeza que gostaria de excluir?','Tem certeza que gostaria de excluir?');
Insert into DWU.BI_CONSTANTES values ('TR_FC_NF','Função não encontrada!','Função não encontrada!');
Insert into DWU.BI_CONSTANTES values ('TR_PE','Sem permissão!','Sem permissão!');
Insert into DWU.BI_CONSTANTES values ('TR_ES_GR','Escolha o grupo!','Escolha o grupo!');
Insert into DWU.BI_CONSTANTES values ('TR_ES_VW','Escolha uma view!','Escolha uma view!');
Insert into DWU.BI_CONSTANTES values ('TR_AG_LE','Agrupadores precisam ter pelo menos um item!','Agrupadores precisam ter pelo menos um item!');
Insert into DWU.BI_CONSTANTES values ('TR_CO_LE','Coluna precisa ter pelo menos um item!','Coluna precisa ter pelo menos um item!');
Insert into DWU.BI_CONSTANTES values ('TR_CO_SL','Selecione uma coluna!','Selecione uma coluna!');
Insert into DWU.BI_CONSTANTES values ('TR_DS_IN','Descrição inválida!','Descrição inválida!');
Insert into DWU.BI_CONSTANTES values ('TR_DS_LE','Descrição deve ter mais de 3 caracteres!','Descrição deve ter mais de 3 caracteres!');
Insert into DWU.BI_CONSTANTES values ('TR_NM_LE','Nome deve ter mais de 3 caracteres!','Nome deve ter mais de 3 caracteres!');
Insert into DWU.BI_CONSTANTES values ('TR_XC','Impossível completar a solicitação!','Impossível completar a solicitação!');
Insert into DWU.BI_CONSTANTES values ('TR_US_FB','Usuário não tem permissão para essa ação!','Usuário não tem permissão para essa ação!');
Insert into DWU.BI_CONSTANTES values ('TR_CD_LE','Código deve ter mais de 3 caracteres!','Código deve ter mais de 3 caracteres!');
Insert into DWU.BI_CONSTANTES values ('TR_QN','Campo da query não pode estar vazio!','Campo da query não pode estar vazio!');
Insert into DWU.BI_CONSTANTES values ('TR_SE','Sessão encerrada!','Sessão encerrada!');
Insert into DWU.BI_CONSTANTES values ('TR_OB_DP','Esse objeto já existe nesta tela!','Esse objeto já existe nesta tela!');
Insert into DWU.BI_CONSTANTES values ('TR_OB_NM','nome do objeto','nome do objeto');
Insert into DWU.BI_CONSTANTES values ('TR_OB_CR','Carregando objeto!','Carregando objeto!');
Insert into DWU.BI_CONSTANTES values ('TR_OB_NO','Nenhum objeto no menu!','Nenhum objeto no menu!');
Insert into DWU.BI_CONSTANTES values ('TR_OB_EX','Remover o objeto de todo o sistema, tem certeza que gostaria de executar?','Remover o objeto de todo o sistema, tem certeza que gostaria de executar?');
Insert into DWU.BI_CONSTANTES values ('TR_US_EX','Remover o usuario da lista e seu acesso, tem certeza que gostaria de executar?','Remover o usuario da lista e seu acesso, tem certeza que gostaria de executar?');
Insert into DWU.BI_CONSTANTES values ('TR_NR','Nenhum resultado encontrado!','Nenhum resultado encontrado!');
Insert into DWU.BI_CONSTANTES values ('TR_LCF','Largura da coluna fixa excede largura da consulta!','Largura da coluna fixa excede largura da consulta!');
Insert into DWU.BI_CONSTANTES values ('TR_II','Campo inválido!','Campo inválido!');
Insert into DWU.BI_CONSTANTES values ('TR_TB','REMOVER TAG DE BUSCA','REMOVER TAG DE BUSCA');
Insert into DWU.BI_CONSTANTES values ('TR_RG','RELATÓRIO FOI GERADO','RELATÓRIO FOI GERADO');
Insert into DWU.BI_CONSTANTES values ('TR_ES_TB','Escolha uma tabela!','Escolha uma tabela!');
Insert into DWU.BI_CONSTANTES values ('TR_SE_LE','Senha precisa ter mais de 6 caracteres e conter letras e números!','Senha precisa ter mais de 6 caracteres e conter letras e números!');
Insert into DWU.BI_CONSTANTES values ('TR_VL_LE','Valor deve ter mais de 3 caracteres!','Valor deve ter mais de 3 caracteres!');
Insert into DWU.BI_CONSTANTES values ('TR_EU','Favor escolher um usuário!','Favor escolher um usuário!');
Insert into DWU.BI_CONSTANTES values ('TR_CA','Cadastro atualizado!','Cadastro atualizado!');
Insert into DWU.BI_CONSTANTES values ('TR_SA','Senha alterada com sucesso!','Senha alterada com sucesso!');
Insert into DWU.BI_CONSTANTES values ('TR_ER_SE','Erro ao alterar a senha!','Erro ao alterar a senha!');
Insert into DWU.BI_CONSTANTES values ('TR_AS','ATUALIZADO COM SUCESSO!','ATUALIZADO COM SUCESSO!');
Insert into DWU.BI_CONSTANTES values ('TR_SP','Usuário sem acesso ao sistema!','Usuário sem acesso ao sistema!');
Insert into DWU.BI_CONSTANTES values ('TR_LE','Login efetuado com sucesso, carregando sistema!','Login efetuado com sucesso, carregando sistema!');
Insert into DWU.BI_CONSTANTES values ('TR_US_IN','Usuário ou senha incorretos!','Usuário ou senha incorretos!');
Insert into DWU.BI_CONSTANTES values ('TR_IU','Favor informar um usuário','Favor informar um usuário');
Insert into DWU.BI_CONSTANTES values ('TR_CA_US','Essa ação vai copiar as regras e permissões do usuário selecionado, tem certeza que deseja proseguir?','Essa ação vai copiar as regras e permissões do usuário selecionado, tem certeza que deseja proseguir?');
Insert into DWU.BI_CONSTANTES values ('TR_LR_US','Essa ação vai limpar as regras e permissões do usuário e copiar do outro usuário selecionado, tem certeza que deseja proseguir?','Essa ação vai limpar as regras e permissões do usuário e copiar do outro usuário selecionado, tem certeza que deseja proseguir?');
Insert into DWU.BI_CONSTANTES values ('TR_NM_LE1','Nome deve ter mais de 1 caracter!','Nome deve ter mais de 1 caracter!');
Insert into DWU.BI_CONSTANTES values ('TR_LO_LE','Campo login precisa ter mais de 3 caracteres!','Campo login precisa ter mais de 3 caracteres!');
Insert into DWU.BI_CONSTANTES values ('TR_LO_LI','login só pode ter letras, números e ponto!','login só pode ter letras, números e ponto!');
Insert into DWU.BI_CONSTANTES values ('TR_EI','Email inválido!','Email inválido!');
Insert into DWU.BI_CONSTANTES values ('TR_AU','ADICIONAR USUÁRIO','ADICIONAR USUÁRIO');
Insert into DWU.BI_CONSTANTES values ('TR_OC','Objeto carregado com sucesso!','Objeto carregado com sucesso!');
Insert into DWU.BI_CONSTANTES values ('TR_ER_MS','Erro ao enviar a mensagem','Erro ao enviar a mensagem');
Insert into DWU.BI_CONSTANTES values ('TR_ER_EX','Erro ao excluir!','Erro ao excluir!');
Insert into DWU.BI_CONSTANTES values ('TR_TD_IN','Campo de data preenchido incorretamente','Campo de data preenchido incorretamente');
Insert into DWU.BI_CONSTANTES values ('TR_FL_DC','Faltam digitar caracteres','Faltam digitar caracteres');
Insert into DWU.BI_CONSTANTES values ('TR_AO','Campos com * são obrigatórios','Campos com * são obrigatórios');
Insert into DWU.BI_CONSTANTES values ('TR_GR','GERANDO RELATÓRIO','GERANDO RELATÓRIO');
Insert into DWU.BI_CONSTANTES values ('TR_TP_MT','MOSTRAR TOTAL','MOSTRAR TOTAL');
Insert into DWU.BI_CONSTANTES values ('TR_TP_SI','SIM','SIM');
Insert into DWU.BI_CONSTANTES values ('TR_TP_NA','NÃO','NÃO');
Insert into DWU.BI_CONSTANTES values ('TR_AM_LL','LIMITE DE LINHAS','LIMITE DE LINHAS');
Insert into DWU.BI_CONSTANTES values ('TR_CS_CD','CONDIÇÕES','CONDIÇÕES');
Insert into DWU.BI_CONSTANTES values ('TR_CS_IA','IGUAL A','IGUAL A');
Insert into DWU.BI_CONSTANTES values ('TR_CS_DD','DIFERENTE DE','DIFERENTE DE');
Insert into DWU.BI_CONSTANTES values ('TR_LO_VA','ATENÇÃO !\nIdentificamos a necessidade de confirmação da sua identidade de acesso ao sistema!\n\nEnviamos um e-mail para o endereço :001 com instruções para confirmação da sua identidade.','ATENÇÃO !\nIdentificamos a necessidade de confirmação da sua identidade de acesso ao sistema!\n\nEnviamos um e-mail para o endereço :001 com instruções para confirmação da sua identidade.');
--
END;
