BEGIN
--
delete from BI_OBJECT_PADRAO_BKP;
insert into BI_OBJECT_PADRAO_BKP (select * from BI_OBJECT_PADRAO);
delete from BI_OBJECT_PADRAO;
--
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','SUB_COLOR','COR_FONTE','Cor/Fonte Subtítulo','#000000','#000000','#000000',null,'N','1','VISUAL','Cor da fonte do subtítulo');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','SUB_COLOR','COR_FONTE','Cor/Fonte Subtítulo','#000000','#000000','#000000',null,'N','1','VISUAL','Cor da fonte do subtítulo');
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','SUB_COLOR','COR_FONTE','Cor/Fonte Subtítulo','#000000','#000000','#000000',null,'N','1','VISUAL','Cor da fonte do subtítulo');
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','SUB_COLOR','COR_FONTE','Cor/Fonte Subtítulo','#000000','#000000','#000000',null,'N','1','VISUAL','Cor da fonte do subtítulo');
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','SUB_COLOR','COR_FONTE','Cor/Fonte Subtítulo','#000000','#000000','#000000',null,'N','1','VISUAL','Cor da fonte do subtítulo');
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','SUB_COLOR','COR_FONTE','Cor/Fonte Subtítulo','#000000','#000000','#000000',null,'N','1','VISUAL','Cor da fonte do subtítulo');
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','SUB_COLOR','COR_FONTE','Cor/Fonte Subtítulo','#000000','#000000','#000000',null,'N','1','VISUAL','Cor da fonte do subtítulo');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','SUB_COLOR','COR_FONTE','Cor/Fonte Subtítulo','#000000','#000000','#000000',null,'N','1','VISUAL','Cor da fonte do subtítulo');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','SUB_COLOR','COR_FONTE','Cor/Fonte Subtítulo','#000000','#000000','#000000',null,'N','1','VISUAL','Cor da fonte do subtítulo');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','SUB_COLOR','COR_FONTE','Cor/Fonte Subtítulo','#000000','#000000','#000000',null,'N','1','VISUAL','Cor da fonte do subtítulo');
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','SUB_COLOR','COR_FONTE','Cor/Fonte Subtítulo','#000000','#000000','#000000',null,'N','1','VISUAL','Cor da fonte do subtítulo');
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','DASH_MARGIN_TOP','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','DASH_MARGIN_TOP','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','DASH_MARGIN_RIGHT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','DASH_MARGIN_RIGHT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','DASH_MARGIN_RIGHT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','DASH_MARGIN_RIGHT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','DASH_MARGIN_RIGHT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','DASH_MARGIN_RIGHT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','DASH_MARGIN_RIGHT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','DASH_MARGIN_RIGHT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('TEXTO','DASH_MARGIN_RIGHT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','ABREVIACAO','CHECK_ONLY','Abreviação numérica','S','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','DRILLT','CHECK_ONLY','Drill do total','S','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','TOP','INTEIRO','Amostra','X','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','ABREVIACAO','CHECK_ONLY','Abreviação numérica','S','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','ABREVIACAO','CHECK_ONLY','Abreviação numérica','S','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','ABREVIACAO','CHECK_ONLY','Abreviação numérica','S','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','NOME_COLUNA','TEXTO','Nome da coluna',null,'gr','rtl',null,'N','99','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','BORDA_COR','COR_GOM','Cor da borda','#999999','gr','color',null,'N','99','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','FILTRO','LOCAL','Interferência','PASSIVO','gr','fil','$opc|PASSIVO|PASSIVO|ISOLADO|ISOLADO|INTERROMPIDO|INTERROMPIDO|COM CORTE|COM CORTE','N',null,'RECURSO','Como o filtro se comporta no objeto');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','BGCOLOR','COR_GOM','Cor de fundo','#FFFFFF','gr','bgcolor',null,'N',null,'VISUAL','Cor do fundo do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','LARGURA','INTEIRO','Largura','800','gr','rtl',null,'N',null,'VISUAL','Largura do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','TEXTO_ACUMULADO','TEXTO','Resto da amostra',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','DASH_MARGIN_TOP','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','DASH_MARGIN_RIGHT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','ABREVIACAO','CHECK_ONLY','Abreviação numérica','S','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','DASH_MARGIN_BOT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','DASH_MARGIN_LEFT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','DASH_MARGIN','INTEIRO','Margem','4px','gr','rtl',null,'N','0','VISUAL','Cima, direita, baixo e esquerda');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','ERR_SD','TEXTO','Mensagem de erro','Sem dados','gr','rtl',null,'N','0','VISUAL','Mensagem quando objeto não tem dados');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','YMIN','TEXTO','Menor valor eixo-y',null,'gr','rtl','$opc|dataMin|menor coluna|0|0','N','1','VISUAL','dataMin para menor coluna');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','NODESC','CHECK_ONLY','Sem descrição','N','gr','rtl',null,'N','1','VISUAL','Esconder descrição e mostrar código');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','ALIGN_TIT','LOCAL','Alinhamento do título','center','vl','rtl','$opc|left|esquerda|right|direita|center|centro','N','0','VISUAL','Posição do alinhamento do título');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','DEGRADE_TIPO','LOCAL','Tipo do degradê','linear','gr','rtl','$opc|linear|linear|radial|radial','N','10','VISUAL','Linear de cima para baixo e radial de dentro para fora');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','ROTACAO','NUMERICO','Rotação da label','30','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','STACKED','CHECK_ONLY','Combinado',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','ESPACAMENTO','TEXTO','Margem interna (T-D-B-E)','30|80|40|80','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','DECIMAL','INTEIRO','Casas decimais','2','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','COR-COLUNA','TEXTO','Cor das colunas',null,'gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','ORDEM','TEXTO','Ordem','1','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','CORES','TEXTO','Cores',null,'gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','AMOSTRA','NUMERICO','Amostragem','0','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','DEGRADE','DEGRADE','Dêgrade','S','gr','rtl',null,'N',null,'VISUAL','Degrade entre a cor do fundo do objeto e do fundo do titulo');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','QUERY_STAT','CHECK_ONLY','Tempo de query','N','gr','rtl',null,'N','1','RECURSO','Alimenta a tabela query_stat com os dados do objeto');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','STACKED_TOTAL','TEXTO','Total do combinado',null,'gr','rtl',null,'N','8','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','NO_RADIUS','CHECK_ONLY','Borda quadrada','N','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','NO_OPTION','CHECK_ONLY','Remover opções','N','gr','rtl',null,'N','0','RECURSO','Remover o menu de opções para usuário');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','ALTURA','INTEIRO','Altura','320','gr','rtl',null,'N',null,'VISUAL','Altura do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','TIT_COLOR','COR_FONTE','Cor/Fonte Título','#000000','ds','color',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','TIT_BGCOLOR','COR_FUNDO','Cor/Fundo Título','#FFFFFF','ds','bgcolor',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','TIT_IT','ITALICO','Título Itálico','normal','ds','fontStyle',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','TIT_BOLD','NEGRITO','Título Negrito','normal','ds','fontWeight',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','TIT_FONT','FONTE','Fonte Título','Arial','ds','fontFamily',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','TIT_SIZE','LOCAL','Tamanho Título','18px','ds','fontSize','$opc|18px|normal|12px|12|14px|14|16px|16|22px|22|28px|28|36px|36|48px|48|72px|72|90px|90','N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','COR_LINHA','COR_GOM','Cor Linha','#FF0000','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','HIDDEN','CHECK_ONLY','Esconder valores','1','gr','rtl','$opc|1|Não|0|Sim','N','0','RECURSO','Esconder valores do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','QUBE','TEXTO','Qube','N','gr','rtl',null,'N','99','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','STACKED_TOTAL','TEXTO','Total do combinado',null,'gr','rtl',null,'N','8','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','META','TEXTAREA','Linha de meta',null,null,'rtl',null,'N','9','RECURSO','Usar pipe para mais de uma linha');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','META','TEXTAREA','Linha de meta',null,null,'rtl',null,'N','9','RECURSO','Usar pipe para mais de uma linha');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','META','TEXTAREA','Linha de meta',null,null,'rtl',null,'N','9','RECURSO','Usar pipe para mais de uma linha');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','ZOOM','CHECK_ONLY','Zoom de dados','N','gr','rtl',null,'N','7','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','ZOOM','CHECK_ONLY','Zoom de dados','N','gr','rtl',null,'N','7','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','ZOOM','CHECK_ONLY','Zoom de dados','N','gr','rtl',null,'N','7','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','META_COR','TEXTO','Cor da meta',null,null,'rtl',null,'N','10','RECURSO','Default usa a cor do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','META_COR','TEXTO','Cor da meta',null,null,'rtl',null,'N','10','RECURSO','Default usa a cor do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','MIN','NUMERICO','Valor inicial','0','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','META_COR','TEXTO','Cor da meta',null,null,'rtl',null,'N','10','RECURSO','Default usa a cor do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','MAX','NUMERICO','Valor final','100','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','VALORES','TEXTAREA','Faixa de valores',null,'gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','CORES','TEXTAREA','Cores',null,'gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','DASH_MARGIN_RIGHT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','DASH_MARGIN_RIGHT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','DASH_MARGIN_BOT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','DASH_MARGIN_BOT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','DASH_MARGIN_TOP','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('TEXTO','DASH_MARGIN_TOP','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','DASH_MARGIN_BOT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','DASH_MARGIN_BOT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','DASH_MARGIN_BOT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','DASH_MARGIN_BOT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','DASH_MARGIN_BOT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','DASH_MARGIN_BOT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','DASH_MARGIN','INTEIRO','Margem','4px','gr','rtl',null,'N','0','VISUAL','Cima, direita, baixo e esquerda');
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','DASH_MARGIN','INTEIRO','Margem','4px','gr','rtl',null,'N','0','VISUAL','Cima, direita, baixo e esquerda');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','DEGRADE_TIPO','LOCAL','Tipo do degradê','linear','gr','rtl','$opc|linear|linear|radial|radial','N','10','VISUAL','Linear de cima para baixo e radial de dentro para fora');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','DEGRADE_TIPO','LOCAL','Tipo do degradê','linear','gr','rtl','$opc|linear|linear|radial|radial','N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','DEGRADE_TIPO','LOCAL','Tipo do degradê','linear','gr','rtl','$opc|linear|linear|radial|radial','N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','DASH_MARGIN','INTEIRO','Margem','4px','gr','rtl',null,'N','0','VISUAL','Cima, direita, baixo e esquerda');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','NAO_REPETIR','CHECK_ONLY','Não repetir valores','N','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FLOAT_PAR','ENCADEADO','TEXTO','Float encadeado',null,'gr','rtl',null,'N','6','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FLOAT_FILTER','ENCADEADO','TEXTO','Float encadeado',null,'gr','rtl',null,'N','6','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FLOAT_PAR','ENCADEADO_COL','TEXTO','Coluna encadeada',null,'gr','rtl',null,'N','6','RECURSO','Coluna usada na condição da query');
Insert into DWU.BI_OBJECT_PADRAO values ('FLOAT_FILTER','ENCADEADO_COL','TEXTO','Coluna encadeada',null,'gr','rtl',null,'N','6','RECURSO','Coluna usada na condição da query');
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','ALTURA','INTEIRO','Altura do gráfico','320','gr','rtl',null,'N','0','VISUAL','Altura do gráfico de porcentagem, aplicavel só no gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','ALIGN_TIT','LOCAL','Alinhamento do título','center','vl','rtl','$opc|left|esquerda|right|direita|center|centro','N','0','VISUAL','Posição do alinhamento do título');
Insert into DWU.BI_OBJECT_PADRAO values ('TEXTO','LARGURA','INTEIRO','Largura','300',null,null,null,'N','3','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BROWSER','UPLOAD','LOCAL','Upload','N','gr','fil','$opc|S|Sim|N|Não|','N','99','RECURSO','Habilita o uso de upload de arquivos no browser');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','CALCULADA_M','TEXTO','Calculada mascara',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','COMANDO','TEXTO','Comando',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','PARAMETROS','TEXTO','Parametros',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','ROTACAO','NUMERICO','Rotação da label','30','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','CALCULADA','TEXTO','Calculada',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','ROTACAO','NUMERICO','Rotação da label','30','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','CALCULADA_N','TEXTO','Calculada nome',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','STACKED','CHECK_ONLY','Combinado',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','ESPACAMENTO','TEXTO','Margem interna (T-D-B-E)','30|80|40|80','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','ESPACAMENTO','TEXTO','Margem interna (T-D-B-E)','30|80|40|80','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','DECIMAL','INTEIRO','Casas decimais','2','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','DECIMAL','INTEIRO','Casas decimais','2','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','DECIMAL','INTEIRO','Casas decimais','2','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','SUBQUERY_ORDEM','NUMERICO','Ordem da subquery','1','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','MAXIMO','INTEIRO','Valor máximo','38000000','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','COR-COLUNA','TEXTO','Cor das colunas',null,'gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','ORDEM','TEXTO','Ordem','1','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','ORDEM','TEXTO','Ordem','1','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','ORDEM','TEXTO','Ordem','1','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','ORDEM','TEXTO','Ordem','1','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','COR-COLUNA','TEXTO','Cor das colunas',null,'gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','CORES','TEXTO','Cores',null,'gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','CORES','TEXTO','Cores',null,'gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','CORES','TEXTO','Cores',null,'gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FLOAT_FILTER','PRIORIDADE','NUMERICO','Prioridade','0','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','HIDDEN','CHECK_ONLY','Esconder valores','1','gr','rtl','$opc|1|Não|0|Sim','N','0','RECURSO','Esconder valores do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','HIDDEN','CHECK_ONLY','Esconder valores','1','gr','rtl','$opc|1|Não|0|Sim','N','0','RECURSO','Esconder valores do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FULL','INTEIRO','Display','0','gr','rtl',null,'N','5','RECURSO','Consulta passa a usar toda a tela do sistema');
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','META_01_GOM','NUMERICO','Meta inicio',null,'gr','rtl',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','META_02_GOM','NUMERICO','Meta fim',null,'gr','rrtl',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','TYPE','LOCAL','FORMATO',null,'gr','rtl','$opc|E|Por estado|C|Por cidade','N','9','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','SUBQUERY-COR','TEXTO','Cor subquery',null,'gr','rtl',null,'N','3','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','AMOSTRA','NUMERICO','Amostragem','0','gr','rtl',null,'S','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','COR-COLUNA','TEXTO','Cor das colunas',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','AMOSTRA','NUMERICO','Amostragem','0','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','AMOSTRA','NUMERICO','Amostragem','0','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','AMOSTRA','NUMERICO','Amostragem','0','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','AMOSTRA','NUMERICO','Amostragem','0','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','COLOR','COR_FONTE','Cor/Fonte Valor','#00AA00','vl','color',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','BGCOLOR','COR_FUNDO','Cor/Fundo Valor','#FFFFFF','vl','bgcolor',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','IT','ITALICO','Valor Itálico',null,'vl','fontStyle',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','BOLD','NEGRITO','Valor Negrito','bold','vl','fontWeight',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','FONT','FONTE','Fonte Valor','Arial','vl','fontFamily',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','SIZE','LOCAL','Tamanho Valor','22px','vl','fontSize','$opc|22px|normal|12px|12|14px|14|16px|16|22px|22|28px|28|36px|36|48px|48|72px|72|90px|90','N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','LARGURA','INTEIRO','Largura','360','gr','lg','$num|9999','N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','ALTURA','INTEIRO','Altura','180','gr','al','$num|9999','N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','COR_ID_01_GOM','COR_GOM','Cor 1','#FF0000','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','TIT_BGCOLOR','COR_FUNDO','Cor/Fundo Título','#CCCCCC','ds','bgcolor',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','TIT_IT','ITALICO','Título Itálico','normal','ds','fontStyle',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','TIT_BOLD','NEGRITO','Título Negrito','bold','ds','fontWeight',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','TIT_FONT','FONTE','Fonte Título','Courier New','ds','fontFamily',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','TIT_SIZE','LOCAL','Tamanho Título','12px','ds','fontSize','$opc|12px|normal|12px|12|14px|14|16px|16|22px|22|28px|28|36px|36|48px|48|72px|72|90px|90','N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','BGCOLOR','COR_FUNDO','Cor de fundo','#FFFFFF','ds','bgcolor',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','LARGURA','INTEIRO','Largura','600','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','ALTURA','INTEIRO','Altura','400','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','DEGRADE','DEGRADE','Dêgrade','S','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','DEGRADE','DEGRADE','Dêgrade','S','gr','rtl',null,'N',null,'VISUAL','Degrade entre a cor do fundo do objeto e do fundo do titulo');
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','DEGRADE','DEGRADE','Dêgrade','S','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','DEGRADE','DEGRADE','Dêgrade','S','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','DEGRADE','DEGRADE','Dêgrade','S','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','BGCOLOR','COR_GOM','Cor de fundo','#FFFFFF','gr','bgcolor',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','DEGRADE','DEGRADE','Dêgrade','S','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('SCRIPT','TIPO','LOCAL','Tipo de comando','SQL','gr','fil','$opc|SQL|SQL|OS|OS|GET|GET','N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','CROSS','CHECK_ONLY','Inverter tabela','N','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','COLUNA_INICIAL','INTEIRO','Coluna Inicial','0','gr','rtl',null,'N','1','RECURSO','Primeira coluna usada no calculo de coluna acumulada');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','COLUNA_FINAL','INTEIRO','Coluna Final','0','gr','rtl',null,'N','1','RECURSO','Ultima coluna usada no calculo de valor acumulado');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','LINHA_ACUMULADA','CHECK_ONLY','Linha Acumulada','N','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','TOTAL_ACUMULADO','CHECK_ONLY','Total Acumulado','N','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FLOAT_FILTER','FLOAT','DEGRADE','Vertical','N','gr','rtl',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','OMITIR_TOT','CHECK_ONLY','Omitir total geral','N','gr','rtl',null,'S','2','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','DEGRADE_TIPO','LOCAL','Tipo do degradê','linear','gr','rtl','$opc|linear|linear|radial|radial','N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','SUBQUERY','TEXTO','Subquery',null,'gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','SANDBOX','CHECK_ONLY','Sem script','N','rg','rtl',null,'N','9','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','AGRUPADORES','TEXTO','Agrupadores',null,'gr','rtl',null,'N','1','RECURSO','Colunas que podem ser usada na troca de coluna');
Insert into DWU.BI_OBJECT_PADRAO values ('FLOAT_FILTER','LIMITADORES','TEXTO','Limitadores',null,'gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','CURSOR','LOCAL','Tipo do cursor','line','gr','rtl','$opc|line|linha|cross|cruz|shadow|sombra','N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','LABEL_CONTEUDO','LOCAL','Conteúdo Label','D','gr','rtl','$opc|A|Ambos|C|Código|D|Descrição','N','21','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','GRAF_AXIS_SHOW','LOCAL_FO','Mostra linha Eixo','false','gr','rtl','$opc|true|Sim|false|Não','N','1','VISUAL','Mostra a linha do eixo que representa os valores.');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','GRAF_AXIS_POSITION_N','LOCAL_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','GRAF_SERIES_TYPE','LOCAL_FO','Representação do Valor','bar','gr','rtl','$opc|bar|Barra|line|Linha','N','3','VISUAL','Representação do valor no gráfico, colunas ou linha.');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','GRAF_SERIES_TYPE_N','LOCAL_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','GRAF_AXIS_MAX','INTEIRO_FO','Limite Max Eixo','0','gr','rtl',null,'N','4','VISUAL','Valor/limite máximo do eixo dos valores.');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','GRAF_AXIS_MAX_N','INTEIRO_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','GRAF_AXIS_INTERVALO','INTEIRO_FO','Intervalo Eixo','0','gr','rtl',null,'N','5','VISUAL','Intervalo do eixo de valores.');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','GRAF_AXIS_INTERVALO_N','INTEIRO_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','GRAF_AXIS_OFFSET','INTEIRO_FO','Margem Eixo','0','gr','rtl',null,'N','6','VISUAL','Margem do eixo com relacao ao grafico.');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','GRAF_AXIS_OFFSET_N','INTEIRO_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','GRAF_AXIS_SHOW','LOCAL_FO','Mostra linha Eixo','false','gr','rtl','$opc|true|Sim|false|Não','N','1','VISUAL','Mostra a linha do eixo que representa os valores.');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','GRAF_AXIS_SHOW_N','LOCAL_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','GRAF_AXIS_POSITION','LOCAL_FO','Posição Linha Eixo','left','gr','rtl','$opc|top|Superior|bottom|Inferior','N','2','VISUAL','Posição da linha do eixo de valores no gráfico.');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','GRAF_AXIS_POSITION_N','LOCAL_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','GRAF_SERIES_TYPE','LOCAL_FO','Representação do Valor','bar','gr','rtl','$opc|bar|Barra|line|Linha','N','3','VISUAL','Representação do valor no gráfico, barras ou linhas.');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','GRAF_SERIES_TYPE_N','LOCAL_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','GRAF_AXIS_MAX','INTEIRO_FO','Limite Max Eixo','0','gr','rtl',null,'N','4','VISUAL','Valor/limite máximo do eixo de valores.');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','GRAF_AXIS_MAX_N','INTEIRO_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','GRAF_AXIS_INTERVALO','INTEIRO_FO','Intervalo Eixo','0','gr','rtl',null,'N','5','VISUAL','Intervalo do eixo de valores.');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','GRAF_AXIS_INTERVALO_N','INTEIRO_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','GRAF_AXIS_OFFSET','INTEIRO_FO','Margem Eixo','0','gr','rtl',null,'N','6','VISUAL','Margem do eixo com relacao ao grafico.');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','GRAF_AXIS_OFFSET_N','INTEIRO_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','EXCEL_MASK','CHECK_ONLY','Retira Mascara Excel','N','gr','rtl',null,'N','99','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','LABEL_CONTEUDO','LOCAL','Conteúdo Label','D','gr','rtl','$opc|A|Ambos|C|Código|D|Descrição','N','11','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','LABEL_CONTEUDO','LOCAL','Conteúdo Label','D','gr','rtl','$opc|A|Ambos|C|Código|D|Descrição','N','11','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','LABEL_CONTEUDO','LOCAL','Conteúdo Label','D','gr','rtl','$opc|A|Ambos|C|Código|D|Descrição','N','2','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','GRAF_SERIES_LABEL_POS','LOCAL_FO','Posição do valor na coluna','top','gr','rtl','$opc|top|Topo|bottom|Base|left|Esquerda|right|Direita|inside|Dentro|insideTop|Dentro-Topo|insideBottom|Dentro-Base|insideLeft|Dentro-Esq.|insideRight|Dentro-Dir.','N','7','VISUAL','Posição do label de valores na coluna.');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','GRAF_SERIES_LABEL_POS_N','LOCAL_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','INVERTE_ORDEM','CHECK_ONLY','Inverte Ordem do Gráfico','N','gr','rtl','$opc|N|Não|S|Sim','N','101','RECURSO','Inverter a ordem das linhas do gráfico.');
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','GRAF_SERIES_LABEL_POS','LOCAL_FO','Posição do label no gráfico','top','gr','rtl','$opc|outside|Fora|inside|Dentro','N','7','VISUAL','Posição do label de valores no gráfico.');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','GRAF_SERIES_LABEL_POS','LOCAL_FO','Posição do valor na barra','top','gr','rtl','$opc|top|Topo|bottom|Base|left|Esquerda|right|Direita|inside|Dentro|insideTop|Dentro-Topo|insideBottom|Dentro-Base|insideLeft|Dentro-Esq.|insideRight|Dentro-Dir.','N','7','VISUAL','Posição do label de valores na barra.');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','GRAF_SERIES_LABEL_POS_N','LOCAL_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','GRAF_SERIES_LABEL_POS_N','LOCAL_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','INVERTE_ORDEM','CHECK_ONLY','Inverte Ordem do Gráfico','N','gr','rtl','$opc|N|Não|S|Sim','N','101','RECURSO','Inverter a ordem das barras do gráfico.');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','TAM_DESC_LABEL_GRAFICO','INTEIRO','Tamanho label gráfico','40','gr','rtl',null,'N','5','VISUAL','Tamanho da descrição da label do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','TAM_DESC_LABEL_GRAFICO','INTEIRO','Tamanho label gráfico','40','gr','rtl',null,'N','5','VISUAL','Tamanho da descrição da label do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','TAM_DESC_LABEL_GRAFICO','INTEIRO','Tamanho label gráfico','40','gr','rtl',null,'N','5','VISUAL','Tamanho da descrição da label do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','TAM_DESC_LABEL_GRAFICO','INTEIRO','Tamanho label gráfico','40','gr','rtl',null,'N','5','VISUAL','Tamanho da descrição da label do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','AGRUPADORES','TEXTO','Agrupadores',null,'gr','rtl',null,'N','1','RECURSO','Colunas que podem ser utilizadas para troca dos agrupadores.');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','AGRUPADORES','TEXTO','Agrupadores',null,'gr','rtl',null,'N','1','RECURSO','Colunas que podem ser utilizadas para troca dos agrupadores.');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','AGRUPADORES','TEXTO','Agrupadores',null,'gr','rtl',null,'N','1','RECURSO','Colunas que podem ser utilizadas para troca dos agrupadores.');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','GRAF_AXIS_MAX_N','INTEIRO_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','GRAF_AXIS_POSITION','LOCAL_FO','Posição Linha Eixo','left','gr','rtl','$opc|left|Esquerda|right|Direita','N','2','VISUAL','Posição da linha do eixo de valor no gráfico.');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','GRAF_AXIS_SHOW','LOCAL_FO','Mostra linha Eixo','false','gr','rtl','$opc|true|Sim|false|Não','N','1','VISUAL','Mostra a linha do eixo que representa os valores.');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','GRAF_AXIS_SHOW_N','LOCAL_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','GRAF_AXIS_INTERVALO','INTEIRO_FO','Intervalo Eixo','0','gr','rtl',null,'N','5','VISUAL','Intervalo do eixo de valores.');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','GRAF_AXIS_POSITION_N','LOCAL_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','GRAF_AXIS_MAX','INTEIRO_FO','Limite Max Eixo','0','gr','rtl',null,'N','4','VISUAL','Valor/limite máximo do eixo dos valores.');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','GRAF_AXIS_INTERVALO_N','INTEIRO_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','GRAF_AXIS_OFFSET','INTEIRO_FO','Margem Eixo','0','gr','rtl',null,'N','6','VISUAL','Margem do eixo com relacao ao grafico.');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','GRAF_AXIS_OFFSET_N','INTEIRO_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','FILTRO_FLOAT','CHECK_ONLY','Bloquear filtro do float','N','gr','rtl',null,'N','0','RECURSO','Bloquar filtro de float');
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','FILTRO_FLOAT','CHECK_ONLY','Bloquear filtro do float','N','gr','rtl',null,'N','0','RECURSO','Bloquar filtro de float');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','FILTRO_FLOAT','CHECK_ONLY','Bloquear filtro do float','N','gr','rtl',null,'N','0','RECURSO','Bloquar filtro de float');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','FILTRO_FLOAT','CHECK_ONLY','Bloquear filtro do float','N','gr','rtl',null,'N','0','RECURSO','Bloquar filtro de float');
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','FILTRO_FLOAT','CHECK_ONLY','Bloquear filtro do float','N','gr','rtl',null,'N','0','RECURSO','Bloquar filtro de float');
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','FILTRO_FLOAT','CHECK_ONLY','Bloquear filtro do float','N','gr','rtl',null,'N','0','RECURSO','Bloquar filtro de float');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','FILTRO_FLOAT','CHECK_ONLY','Bloquear filtro do float','N','gr','rtl',null,'N','0','RECURSO','Bloquar filtro de float');
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','FILTRO_TELA','CHECK_ONLY','Bloquear filtro da tela','N','gr','rtl',null,'N','7','RECURSO','Bloquar filtro de tela');
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','FILTRO_TELA','CHECK_ONLY','Bloquear filtro da tela','N','gr','rtl',null,'N','7','RECURSO','Bloquar filtro de tela');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','FILTRO_TELA','CHECK_ONLY','Bloquear filtro da tela','N','gr','rtl',null,'N','7','RECURSO','Bloquar filtro de tela');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','FILTRO_TELA','CHECK_ONLY','Bloquear filtro da tela','N','gr','rtl',null,'N','7','RECURSO','Bloquar filtro de tela');
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','FILTRO_TELA','CHECK_ONLY','Bloquear filtro da tela','N','gr','rtl',null,'N','7','RECURSO','Bloquar filtro de tela');
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','FILTRO_TELA','CHECK_ONLY','Bloquear filtro da tela','N','gr','rtl',null,'N','7','RECURSO','Bloquar filtro de tela');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','FILTRO_TELA','CHECK_ONLY','Bloquear filtro da tela','N','gr','rtl',null,'N','7','RECURSO','Bloquar filtro de tela');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','GRAF_AXIS_SHOW_N','LOCAL_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','GRAF_AXIS_POSITION','LOCAL_FO','Posição Linha Eixo','left','gr','rtl','$opc|left|Esquerda|right|Direita','N','2','VISUAL','Posição da linha do eixo de valor no gráfico.');
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','FILTRO_DRILL','CHECK_ONLY','Bloquear filtro da drill','N','gr','rtl',null,'N','99','RECURSO','Bloquar filtro de drill');
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','FILTRO_DRILL','CHECK_ONLY','Bloquear filtro da drill','N','gr','rtl',null,'N','99','RECURSO','Bloquar filtro de drill');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','FILTRO_DRILL','CHECK_ONLY','Bloquear filtro da drill','N','gr','rtl',null,'N','99','RECURSO','Bloquar filtro de drill');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','FILTRO_DRILL','CHECK_ONLY','Bloquear filtro da drill','N','gr','rtl',null,'N','99','RECURSO','Bloquar filtro de drill');
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','FILTRO_DRILL','CHECK_ONLY','Bloquear filtro da drill','N','gr','rtl',null,'N','99','RECURSO','Bloquar filtro de drill');
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','FILTRO_DRILL','CHECK_ONLY','Bloquear filtro da drill','N','gr','rtl',null,'N','99','RECURSO','Bloquar filtro de drill');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','FILTRO_DRILL','CHECK_ONLY','Bloquear filtro da drill','N','gr','rtl',null,'N','99','RECURSO','Bloquar filtro de drill');
Insert into DWU.BI_OBJECT_PADRAO values ('FLOAT_PAR','PRIORIDADE','NUMERICO','Prioridade','0','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FLOAT_PAR','LIMITADORES','TEXTO','Limitadores',null,'gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FLOAT_PAR','ORDEM','LOCAL','Ordem',null,'ds','rtl','$opc|1|código crescente|2|código decrescente|3|descrição crescente|4|descrição decrescente','N','5','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','CURSOR','LOCAL','Tipo do cursor','line','gr','rtl','$opc|line|linha|cross|cruz|shadow|sombra','N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','CURSOR','LOCAL','Tipo do cursor','line','gr','rtl','$opc|line|linha|cross|cruz|shadow|sombra','N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','MARK-MAX','CHECK_ONLY','Mostrar máximo','N','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','MARK-MIN','CHECK_ONLY','Mostrar mínimo','N','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','MARK-MEDIA','CHECK_ONLY','Mostrar média','N','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','MARK-MAX','CHECK_ONLY','Mostrar máximo','N','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','MARK-MIN','CHECK_ONLY','Mostrar mínimo','N','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','MARK-MEDIA','CHECK_ONLY','Mostrar média','N','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','CHAMADA','TEXTO','Chamada',null,'gr','rtl',null,'N','3','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','COMANDO','TEXTO','Comando',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','EXECUCAO','TEXTO','Limitar Execução',null,'ds','rtl',null,'N','4','RECURSO','Limita o número de chamadas de execução');
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','PARAMETROS','TEXTO','Parametros',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','DISPLAY_TITLE','LOCAL','Esconder título','inline','ds','rtl','$opc|inline|mostrar|none|esconder','N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','DISPLAY_TITLE','CHECK_ONLY','Esconder título','S','ds','rtl','$opc|S|mostrar|N|esconder','N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','TIPO','LOCAL','TIPO','pie','gr','rtl','$opc|pie|Pizza|donut|Rosca|funnel|Funil','N','20','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','BORDA_COR','COR_GOM','Cor da borda','#999999','gr','color',null,'N','99','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','BORDA_COR','COR_GOM','Cor da borda','#999999','gr','color',null,'N','99','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','BORDA_COR','COR_GOM','Cor da borda','#999999','gr','color',null,'N','99','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','BORDA_COR','COR_GOM','Cor da borda','#999999','gr','color',null,'N','99','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','BORDA_COR','COR_GOM','Cor da borda','#999999','gr','color',null,'N','99','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','BORDA_COR','COR_GOM','Cor da borda','#999999','gr','color',null,'N','99','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','BORDA_COR','COR_GOM','Cor da borda','#999999','gr','color',null,'N','99','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','BORDA_COR','COR_GOM','Cor da borda','transparent','gr','color',null,'N','99','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('RELATORIO','BORDA_COR','COR_GOM','Cor da borda','#999999','gr','color',null,'N','99','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FLOAT_PAR','MASCARA','TEXTO','Máscara',null,'gr','rtl',null,'N','8','RECURSO','Adiciona uma máscara para o float_par. Ex: 999G999G999D99 , 999.999.999,99');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','BLOQ_OBJ','CHECK_ONLY','Bloquear Objeto','N','gr','rtl','$opc|N|Não|S|Sim','N','34','RECURSO','Bloquear objeto para usuário.');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','COR','COR_FUNDO','Cor do texto','#333333','gr','color',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','COR','COR_FUNDO','Cor do texto','#333333','gr','color',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','COR','COR_FUNDO','Cor do texto','#333333','gr','color',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','COR','COR_FUNDO','Cor do texto','#333333','gr','color',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','TIT_IT','ITALICO','Título Itálico','normal','ds','fontStyle',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','TIT_BGCOLOR','COR_FUNDO','Cor/Fundo Título','transparent','ds','bgcolor',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','TIT_BOLD','NEGRITO','Título Negrito','bold','ds','fontWeight',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','TIT_FONT','FONTE','Fonte Título','Courier New','ds','fontFamily',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','TIT_COLOR','COR_FONTE','Cor/Fonte Título','#000000','ds','color',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','TIT_SIZE','LOCAL','Tamanho Título','18px','ds','fontSize','$opc|18px|normal|12px|12|14px|14|16px|16|22px|22|28px|28|36px|36|48px|48|72px|72|90px|90','N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','ALIGN_TIT','LOCAL','Alinhamento do título','left','vl','rtl','$opc|left|esquerda|right|direita|center|centro','N','0','VISUAL','Posição do alinhamento do título');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','TEXTO_ACUMULADO','TEXTO','Resto da amostra',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','UM','INTEIRO','Unidade de Medida',null,'ds','rtl',null,'N','4','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','UM','INTEIRO','Unidade de Medida',null,'ds','rtl',null,'N','4','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','UM','INTEIRO','Unidade de Medida',null,'ds','rtl',null,'N','4','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','INVERTE_ORDEM','CHECK_ONLY','Inverte Ordem do Gráfico','N','gr','rtl','$opc|N|Não|S|Sim','N','101','RECURSO','Inverter a ordem das colunas do gráfico.');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','BLOQ_OBJ','CHECK_ONLY','Bloquear Objeto','N','gr','rtl','$opc|N|Não|S|Sim','N','34','RECURSO','Bloquear objeto para usuário.');
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','BLOQ_OBJ','CHECK_ONLY','Bloquear Objeto','N','gr','rtl','$opc|N|Não|S|Sim','N','34','RECURSO','Bloquear objeto para usuário.');
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','BLOQ_OBJ','CHECK_ONLY','Bloquear Objeto','N','gr','rtl','$opc|N|Não|S|Sim','N','34','RECURSO','Bloquear objeto para usuário.');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','DISPLAY_TITLE','CHECK_ONLY','Esconder título','N','ds','rtl','$opc|S|mostrar|N|esconder','S','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','BLOQ_OBJ','CHECK_ONLY','Bloquear Objeto','N','gr','rtl','$opc|N|Não|S|Sim','N','34','RECURSO','Bloquear objeto para usuário.');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','BLOQ_OBJ','CHECK_ONLY','Bloquear Objeto','N','gr','rtl','$opc|N|Não|S|Sim','N','34','RECURSO','Bloquear objeto para usuário.');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','BLOQ_OBJ','CHECK_ONLY','Bloquear Objeto','N','gr','rtl','$opc|N|Não|S|Sim','N','34','RECURSO','Bloquear objeto para usuário.');
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','ABREVIACAO','CHECK_ONLY','Abreviação numérica','N','gr','rtl',null,'N','25','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','UM','INTEIRO','Unidade de Medida',null,'ds','rtl',null,'N','4','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','GRAF_AXIS_NRO','INTEIRO_FO','Número do Eixo','0','gr','rtl',null,'N','7','VISUAL','Número do eixo de referência para o valor.');
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','GRAF_AXIS_NRO_N','INTEIRO_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','GRAF_AXIS_NRO','INTEIRO_FO','Número do Eixo','0','gr','rtl',null,'N','7','VISUAL','Número do eixo de referência para o valor.');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','GRAF_AXIS_NRO_N','INTEIRO_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','GRAF_AXIS_NRO','INTEIRO_FO','Número do Eixo','0','gr','rtl',null,'N','7','VISUAL','Número do eixo de referência para o valor.');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','GRAF_AXIS_NRO_N','INTEIRO_FO',null,null,'gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','APLICA_DESTAQUE','LOCAL','Aplicar destaque','titulo','gr','rtl','$opc|titulo|Título|valor|Valor|ambos|Ambos','N','2','VISUAL','Aplicar o destaque somente no Título, valor ou Ambos.');
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','DASH_MARGIN_LEFT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','DASH_MARGIN_LEFT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','DASH_MARGIN_LEFT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','DASH_MARGIN_LEFT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','DASH_MARGIN_LEFT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','DASH_MARGIN_LEFT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','DASH_MARGIN_LEFT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('TEXTO','DASH_MARGIN_LEFT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','DASH_MARGIN_LEFT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','DASH_MARGIN_LEFT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','DASH_MARGIN','INTEIRO','Margem','4px','gr','rtl',null,'N','0','VISUAL','Cima, direita, baixo e esquerda');
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','DEGRADE_TIPO','LOCAL','Tipo do degradê','linear','gr','rtl','$opc|linear|linear|radial|radial','N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','CASCATA','CHECK_ONLY','Efeito de cascata','N','gr','rtl',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','IMG','TEXTO','Icone',null,'gr','rtl',null,'N','2','ICONE',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','IMG_BGCOLOR','COR_FUNDO','Cor do fundo do icone','#EEEEEECC','vl','rtl',null,'N','28','ICONE',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','IMG_BORDA','COR_FUNDO','Borda do icone','#555','vl','rtl',null,'N','29','ICONE',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','IMG_ESPACAMENTO','INTEIRO','Espaçamento do icone','18px','vl','rtl',null,'N','30','ICONE',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','IMG_ALTURA','INTEIRO','Altura do icone','auto','vl','rtl',null,'N','27','ICONE',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','IMG_LARGURA','INTEIRO','Largura do icone','auto','vl','rtl',null,'N','31','ICONE',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','IMG_RADIUS','INTEIRO','Borda arredondada','40px','vl','rtl',null,'N','33','ICONE',null);
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','EXECUCAO','TEXTO','Limitar Execução',null,'ds','rtl',null,'N','4','RECURSO','Limita o número de chamadas de execução');
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','IMG_OPTION','CHECK_ONLY','Usar icone','N','gr','rtl',null,'N','32','ICONE',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FLOAT_PAR','VAZIO','LOCAL','Vazio','N','gr','rtl','$opc|N|Não|S|Sim','N','5','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','ERR_SD','TEXTO','Mensagem de erro','Sem dados','gr','rtl',null,'N','0','VISUAL','Mensagem quando objeto não tem dados');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','ERR_SD','TEXTO','Mensagem de erro','Sem dados','gr','rtl',null,'N','0','VISUAL','Mensagem quando objeto não tem dados');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','ERR_SD','TEXTO','Mensagem de erro','Sem dados','gr','rtl',null,'N','0','VISUAL','Mensagem quando objeto não tem dados');
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','ERR_SD','TEXTO','Mensagem de erro','Sem dados','gr','rtl',null,'N','0','VISUAL','Mensagem quando objeto não tem dados');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','TOT_BOLD','NEGRITO','Total Negrito','normal','ds','fontWeight',null,'N','99','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','HEAD_BOLD','NEGRITO','Cabeçalho Negrito','normal','ds','fontWeight',null,'N','99','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','YMIN','TEXTO','Menor valor eixo-y',null,'gr','rtl','$opc|dataMin|menor coluna|0|0','N','1','VISUAL','dataMin para menor coluna');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','YMIN','TEXTO','Menor valor eixo-y','0','gr','rtl','$opc|dataMin|menor coluna|0|0','N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FONT_FAMILY','LOCAL','Fonte da consulta','Arial','gr','fil','$opc|Courier|Courier|Verdana|Verdana|Monospace|Monospace|Tahoma|Tahoma|Arial|Arial|Montserrat|Montserrat','S','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','UM','INTEIRO','Unidade de Medida',null,'ds','rtl',null,'N','4','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FLOAT_FILTER','ORDEM','LOCAL','Ordem',null,'ds','rtl','$opc|1|código crescente|2|código decrescente|3|descrição crescente|4|descrição decrescente','N','5','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','NODESC','CHECK_ONLY','Sem descrição','N','gr','rtl',null,'N','1','VISUAL','Esconder descrição e mostrar código');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','NODESC','CHECK_ONLY','Sem descrição','N','gr','rtl',null,'N','1','VISUAL','Esconder descrição e mostrar código');
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','BGCOLOR','COR_GOM','Cor do Fundo','transparent','vl','bgcolor',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','LARGURA','INTEIRO','Largura máxima','500','gr','height',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','ALTURA','INTEIRO','Altura máxima','300','gr','width',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','TIT_COLOR','COR_FONTE','Cor/Fonte Título','#000000','ds','color',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','TIT_BGCOLOR','COR_FUNDO','Cor/Fundo Título','transparent','ds','bgcolor',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','TIT_IT','ITALICO','Título Itálico','normal','ds','fontStyle',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','TIT_BOLD','NEGRITO','Título Negrito','bold','ds','fontWeight',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','TIT_FONT','FONTE','Fonte Título','Courier New','ds','fontFamily',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','TIT_SIZE','LOCAL','Tamanho Título','18px','ds','fontSize','$opc|18px|normal|12px|12|14px|14|16px|16|22px|22|28px|28|36px|36|48px|48|72px|72|90px|90','N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FILTRO_TELA','CHECK_ONLY','Bloquear filtro da tela','N','gr','rtl',null,'N','7','RECURSO','Bloquar filtro de tela');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FILTRO_DRILL','CHECK_ONLY','Bloquear filtro da drill','N','gr','rtl',null,'N','99','RECURSO','Bloquar filtro de drill');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FILTRO_FLOAT','CHECK_ONLY','Bloquear filtro do float','N','gr','rtl',null,'N','0','RECURSO','Bloquar filtro de float');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','ALIGN_TIT','LOCAL','Alinhamento do título','center','vl','rtl','$opc|left|esquerda|right|direita|center|centro','S','0','VISUAL','Posição do alinhamento do título');
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','ALIGN_TIT','LOCAL','Alinhamento do título','center','vl','rtl','$opc|left|esquerda|right|direita|center|centro','N','0','VISUAL','Posição do alinhamento do título');
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','ALIGN_TIT','LOCAL','Alinhamento do título','center','vl','rtl','$opc|left|esquerda|right|direita|center|centro','N','0','VISUAL','Posição do alinhamento do título');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','ALIGN_TIT','LOCAL','Alinhamento do título','center','vl','rtl','$opc|left|esquerda|right|direita|center|centro','N','0','VISUAL','Posição do alinhamento do título');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','ALIGN_TIT','LOCAL','Alinhamento do título','center','vl','rtl','$opc|left|esquerda|right|direita|center|centro','N','0','VISUAL','Posição do alinhamento do título');
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','ALIGN_TIT','LOCAL','Alinhamento do título','center','vl','rtl','$opc|left|esquerda|right|direita|center|centro','N','0','VISUAL','Posição do alinhamento do título');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','GRID_COLOR','COR_GOM','Cor da grade','#555555','gr','bgcolor',null,'N','0','VISUAL','Cor se a grade estiver ativa na consulta');
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','META_HINT','TEXTO','Texto do meta','META','gr','rtl',null,'N','0','VISUAL','Texto a ser usado no lugar do hint META');
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','RAIO','NUMERICO','Raio','180','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('TEXTO','BORDA_COR','COR_FUNDO','Cor da borda','transparent','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('TEXTO','MARQUEE','CHECK_ONLY','Marquee','N',null,null,null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','META','INTEIRO','Meta de valor',null,'gr','rtl',null,'N','0','VISUAL','Valor da meta');
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','LARGURA','INTEIRO','Largura do gráfico','400','gr','rtl',null,'N','0','VISUAL','Largura do gráfico de porcentagem, aplicavel só no gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','QUERY_STAT','CHECK_ONLY','Tempo de query','N','gr','rtl',null,'N','1','RECURSO','Alimenta a tabela query_stat com os dados do objeto');
Insert into DWU.BI_OBJECT_PADRAO values ('SCREEN','QUERY_STAT','CHECK_ONLY','Tempo de query','N','gr','rtl',null,'N','1','RECURSO','Alimenta a tabela query_stat com os dados do objeto');
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','CORES','TEXTO','Cores',null,'gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','DASH_MARGIN_BOT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','DASH_MARGIN_LEFT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','DASH_MARGIN','INTEIRO','Margem','4px','gr','rtl',null,'N','0','VISUAL','Cima, direita, baixo e esquerda');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','DASH_MARGIN','INTEIRO','Margem','4px','gr','rtl',null,'N','0','VISUAL','Cima, direita, baixo e esquerda');
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','DASH_MARGIN','INTEIRO','Margem','4px','gr','rtl',null,'N','0','VISUAL','Cima, direita, baixo e esquerda');
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','DASH_MARGIN_BOT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('TEXTO','DASH_MARGIN_BOT','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','DASH_MARGIN','INTEIRO','Margem','4px','gr','rtl',null,'N','0','VISUAL','Cima, direita, baixo e esquerda');
Insert into DWU.BI_OBJECT_PADRAO values ('TEXTO','DASH_MARGIN','INTEIRO','Margem','4px','gr','rtl',null,'N','0','VISUAL','Cima, direita, baixo e esquerda');
Insert into DWU.BI_OBJECT_PADRAO values ('SCRIPT','COMPATIBILIDADE','TEXTO','Compatibilidade',null,'gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FONT_SIZE','LOCAL','Tamanho da fonte','12px','gr','fil','$opc|8px|8|9px|9|10px|10|12px|12|14px|14|16px|16|22px|22|28px|28|36px|36|48px|48|54px|54|60px|60|66px|66|72px|72|100px|100','S','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','NO_RADIUS','CHECK_ONLY','Borda quadrada','N','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','NO_RADIUS','CHECK_ONLY','Borda quadrada','N','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','NO_RADIUS','CHECK_ONLY','Borda quadrada','N','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','NO_RADIUS','CHECK_ONLY','Borda quadrada','N','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','NO_RADIUS','CHECK_ONLY','Borda quadrada','N','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','NO_RADIUS','CHECK_ONLY','Borda quadrada','N','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','NO_RADIUS','CHECK_ONLY','Borda quadrada','N','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','NO_RADIUS','CHECK_ONLY','Borda quadrada','N','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','NO_OPTION','CHECK_ONLY','Remover opções','N','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','NO_OPTION','CHECK_ONLY','Remover opções','N','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','NO_OPTION','CHECK_ONLY','Remover opções','N','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','NO_OPTION','CHECK_ONLY','Remover opções','N','gr','rtl',null,'N','0','RECURSO','Remover o menu de opções para usuário');
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','NO_OPTION','CHECK_ONLY','Remover opções','N','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','NO_OPTION','CHECK_ONLY','Remover opções','N','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','NO_OPTION','CHECK_ONLY','Remover opções','N','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','NO_OPTION','CHECK_ONLY','Remover opções','N','gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','TOTAL_SEPARADO','CHECK_ONLY','Total Acumulado Separado','N','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('SCRIPT','EXECUCAO','LOCAL','Modo de execução','EXCLUSIVA','gr','fil','$opc|EXCLUSIVA|EXCLUSIVA|USUARIO|USUARIO|LIVRE|LIVRE','N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('SCRIPT','COMANDO','TEXTO','Comando',null,'gr','fil',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('SCRIPT','PARAMETROS','TEXTO','Parâmetros',null,'gr','fil',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','RESUMIDO','CHECK_ONLY','Resumido','N','gr','rtl',null,'N',null,'RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FLOAT_FILTER','MULTI','CHECK_ONLY','Multi seleção','S','gr','rtl',null,'N','6','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','LARGURA','INTEIRO','Largura máxima','4000','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FIXED-N','INTEIRO','Colunas fixas','100','gr','rtl',null,'S','5','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','ALTURA','INTEIRO','Altura','320','gr','rtl',null,'N',null,'VISUAL','Altura do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','TIT_COLOR','COR_FONTE','Cor/Fonte Título','#000000','ds','color',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','TIT_BGCOLOR','COR_FUNDO','Cor/Fundo Título','#FFFFFF','ds','bgcolor',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','TIT_IT','ITALICO','Título Itálico','normal','ds','fontStyle',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','TIT_BOLD','NEGRITO','Título Negrito','normal','ds','fontWeight',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','TIT_FONT','FONTE','Fonte Título','Arial','ds','fontFamily',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','TIT_SIZE','LOCAL','Tamanho Título','18px','ds','fontSize','$opc|18px|normal|12px|12|14px|14|16px|16|22px|22|28px|28|36px|36|48px|48|72px|72|90px|90','N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','ERR_SD','TEXTO','Mensagem de erro','Sem dados','gr','rtl',null,'N','1','VISUAL','Mensagem quando objeto não tem dados');
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR',   'ERR_SD','TEXTO','Mensagem de erro','N/A','gr','rtl',null,'N','1','VISUAL','Mensagem quando objeto não tem dados');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','TIT_COLOR','COR_FONTE','Cor/Fonte Título','#000000','ds','color',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','TIT_BGCOLOR','COR_FUNDO','Cor/Fundo Título','#999999','ds','bgcolor',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','TIT_IT','ITALICO','Título Itálico','normal','ds','fontStyle',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','TIT_BOLD','NEGRITO','Título Negrito','bold','ds','fontWeight',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','TIT_FONT','FONTE','Fonte Título','Arial','ds','fontFamily',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','TIT_SIZE','LOCAL','Tamanho Titulo','18px','ds','fontSize','$opc|18px|normal|12px|12|14px|14|16px|16|22px|22|28px|28|36px|36|48px|48|72px|72|90px|90','N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','UM','INTEIRO','Unidade de medida',null,'ds','rtl',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','COR_LINHA','COR_GOM','Cor Linha','#FF0000','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('TEXTO','COLOR','COR_FONTE','Cor/Fonte Texto','#000000','vl','color',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('TEXTO','BGCOLOR','COR_FUNDO','Cor/Fundo Texto','#FFFFFF','vl','bgcolor',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('TEXTO','IT','ITALICO','Texto Itálico',null,'ds','fontStyle',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('TEXTO','BOLD','NEGRITO','Texto Negrito','bold','ds','fontWeight',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('TEXTO','FONT','FONTE','Fonte Texto','Verdana','vl','fontFamily',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('TEXTO','SIZE','LOCAL','Tamanho Texto','32px','vl','fontSize','$opc|16px|normal|12px|12|14px|14|16px|16|22px|22|28px|28|32px|32|36px|36|48px|48|72px|72|90px|90','N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','ALTURA','INTEIRO','Altura máxima','550','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','ROTULOS','CHECK_ONLY','Exibir Rotulos','S','gr','rtl',null,'N',null,'RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','ORDEM','INTEIRO','Ordem','1','gr','rtl',null,'N',null,'RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','TP_GRUPO','LOCAL','Agrupamento','ROLL','gr','loc','$opc|ROLL|Rollup|CUBE|Cube|GROUP|Group','N',null,'RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('ICONE','CHAMADA','TEXTO','Chamada',null,'gr','rtl',null,'N','3','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','HIDDEN','CHECK_ONLY','Esconder valores','1','gr','rtl','$opc|1|Não|0|Sim','N','0','RECURSO','Esconder valores do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','BGCOLOR','COR_GOM','Cor do Fundo','#FFFFFF','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','LARGURA','INTEIRO','Largura','500','gr','height',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','ALTURA','INTEIRO','Altura','300','gr','width',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','TIT_COLOR','CFREE_FONTE','Cor/Fonte Título','FFFFFF','ds','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','TIT_BGCOLOR','CFREE_FUNDO','Cor/Fundo Título','#000000','ds','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','TIT_IT','ITALICO','Título Itálico','normal','ds','fontStyle',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','TIT_BOLD','NEGRITO','Título Negrito','bold','ds','fontWeight',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','TIT_FONT','FONTE','Fonte Título','Courier New','ds','fontFamily',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FILE','TIT_SIZE','LOCAL','Tamanho Título','12px','ds','fontSize','$opc|12px|normal|12px|12|14px|14|16px|16|22px|22|28px|28|36px|36|48px|48|72px|72|90px|90','N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','HIDDEN','CHECK_ONLY','Esconder valores','1','gr','rtl','$opc|1|Não|0|Sim','N','0','RECURSO','Esconder valores do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('FLOAT_PAR','FORMATO','LOCAL','Formato','0','gr','rtl','$opc|0|Código e descrição|1|Somente código|2|Somente descrição','N','5','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','REORDER','LOCAL','Bloquear reordem','N','gr','fil','$opc|N|Não|S|Sim','N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','TIT_BOLD','NEGRITO','Título Negrito','bold','ds','fontWeight',null,'S','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','FILTRO','LOCAL','Interferência','PASSIVO','gr','fil','$opc|PASSIVO|PASSIVO|ISOLADO|ISOLADO|INTERROMPIDO|INTERROMPIDO|COM CORTE|COM CORTE','N',null,'RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','DASH_MARGIN','INTEIRO','Margem','4px','gr','rtl',null,'N','0','VISUAL','Cima, direita, baixo e esquerda');
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','DEGRADE_TIPO','LOCAL','Tipo do degradê','linear','gr','rtl','$opc|linear|linear|radial|radial','N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','FILTRO','LOCAL','Interferência','PASSIVO','gr','fil','$opc|PASSIVO|PASSIVO|ISOLADO|ISOLADO|INTERROMPIDO|INTERROMPIDO|COM CORTE|COM CORTE','N','1','RECURSO','Como o filtro se comporta no objeto');
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','DASH_MARGIN','INTEIRO','Margem','4px','gr','rtl',null,'N','0','VISUAL','Cima, direita, baixo e esquerda');
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','ESTADOS','TEXTO','Estados',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','QUERY_STAT','CHECK_ONLY','Tempo de query','N','gr','rtl',null,'N','1','RECURSO','Alimenta a tabela query_stat com os dados do objeto');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','QUERY_STAT','CHECK_ONLY','Tempo de query','N','gr','rtl',null,'N','1','RECURSO','Alimenta a tabela query_stat com os dados do objeto');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','QUERY_STAT','CHECK_ONLY','Tempo de query','N','gr','rtl',null,'N','1','RECURSO','Alimenta a tabela query_stat com os dados do objeto');
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','QUERY_STAT','CHECK_ONLY','Tempo de query','N','gr','rtl',null,'N','1','RECURSO','Alimenta a tabela query_stat com os dados do objeto');
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','QUERY_STAT','CHECK_ONLY','Tempo de query','N','gr','rtl',null,'N','1','RECURSO','Alimenta a tabela query_stat com os dados do objeto');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','SO_TOT','CHECK_ONLY','Somente total geral','N','gr','rtl',null,'S','3','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','DECIMAL','INTEIRO','Casas decimais','2','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','MARK-MAX','CHECK_ONLY','Mostrar máximo','N','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','MARK-MIN','CHECK_ONLY','Mostrar mínimo','N','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','MARK-MEDIA','CHECK_ONLY','Mostrar média','N','gr','rtl',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','NOME_PIVOT','TEXTO','Nome no pivot','TOTAL','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','FILTRO','LOCAL','Interferência','PASSIVO','gr','fil','$opc|PASSIVO|PASSIVO|ISOLADO|ISOLADO|INTERROMPIDO|INTERROMPIDO|COM CORTE|COM CORTE','N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','FILTRO','LOCAL','Interferência','PASSIVO','gr','fil','$opc|PASSIVO|PASSIVO|ISOLADO|ISOLADO|INTERROMPIDO|INTERROMPIDO|COM CORTE|COM CORTE','N',null,'RECURSO','Como o filtro se comporta no objeto');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FILTRO','LOCAL','Interferência','PASSIVO','gr','fil','$opc|PASSIVO|PASSIVO|ISOLADO|ISOLADO|INTERROMPIDO|INTERROMPIDO|COM CORTE|COM CORTE','N',null,'RECURSO','Como o filtro se comporta no objeto');
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','FILTRO','LOCAL','Interferência','PASSIVO','gr','fil','$opc|PASSIVO|PASSIVO|ISOLADO|ISOLADO|INTERROMPIDO|INTERROMPIDO|COM CORTE|COM CORTE','N',null,'RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','FILTRO','LOCAL','Interferência','PASSIVO','gr','fil','$opc|PASSIVO|PASSIVO|ISOLADO|ISOLADO|INTERROMPIDO|INTERROMPIDO|COM CORTE|COM CORTE','N',null,'RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','BGCOLOR','COR_GOM','Cor do Fundo','#FFFFFF','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','LARGURA','INTEIRO','Largura máxima','500','gr','height',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('IMAGE','ALTURA','INTEIRO','Altura máxima','300','gr','width',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','XML','LOCAL','Gerar xml','N','gr','fil','$opc|S|Sim|N|Não|O|Somente xml','N','5','RECURSO','Monta a estrutura em xml para fazer download');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','VISIVEL','TEXTO','Colunas invisíveis',null,'gr','rtl',null,'N','6','RECURSO','Coluna visivel nesta consulta');
Insert into DWU.BI_OBJECT_PADRAO values ('GEOMAPA','TABELA','TEXTO','Tabela',null,'gr','rtl',null,'N','5','RECURSO','Tabela usada no mapa');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FUNDO_VALOR','COR_GOM','Fundo objeto','#DDDDDD','gr','bgcolor',null,'N','5','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','BGCOLOR','COR_GOM','Cor de fundo','#FFFFFF','gr','bgcolor',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','TIT_COLOR','COR_FONTE','Cor/Fonte Título','#000000','ds','color',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','TIT_BGCOLOR','COR_FUNDO','Cor/Fundo Título','#999999','ds','bgcolor',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','TIT_IT','ITALICO','Título Itálico','normal','ds','fontStyle',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','TIT_BOLD','NEGRITO','Título Negrito','normal','ds','fontWeight',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','TIT_FONT','FONTE','Fonte Título','Arial','ds','fontFamily',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','TIT_SIZE','LOCAL','Tamanho Título','18px','ds','fontSize','$opc|18px|normal|12px|12|14px|14|16px|16|22px|22|28px|28|36px|36|48px|48|72px|72|90px|90','N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','COLOR','COR_FONTE','Cor/Fonte Valor','#000000','ds','color',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','IT','ITALICO','Valor Itálico',null,'ds','fontStyle',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','BOLD','NEGRITO','Valor Negrito','normal','ds','fontWeight',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','FONT','FONTE','Fonte Valor','Arial','ds','fontFamily',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','SIZE','LOCAL','Tamanho Valor','18px','ds','fontSize','$opc|18px|normal|12px|12|14px|14|16px|16|22px|22|28px|28|36px|36|48px|48|72px|72|90px|90','N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','TIT_COLOR','COR_FONTE','Cor/Fonte Título','#000000','ds','color',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','TIT_BGCOLOR','COR_FUNDO','Cor/Fundo Título','#FFFFFF','ds','bgcolor',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','TIT_IT','ITALICO','Título Itálico','normal','ds','fontStyle',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','TIT_BOLD','NEGRITO','Título Negrito','bold','ds','fontWeight',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','TIT_FONT','FONTE','Fonte Título','Arial','ds','fontFamily',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','TIT_SIZE','LOCAL','Tamanho Título','16px','ds','fontSize','$opc|16px|normal|12px|12|14px|14|16px|16|22px|22|28px|28|36px|36|48px|48|72px|72|90px|90','N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','TOTAL_SEPARADO_TEXTO','INTEIRO','Total Separado',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','TOTAL_GERAL_TEXTO','INTEIRO','Total Geral',null,'gr','rtl',null,'S','0','RECURSO','Preencher este campo força o número de colunas fixas para o máximo');
Insert into DWU.BI_OBJECT_PADRAO values ('GEOMAPA','NAME','TEXTO','Coluna do nome',null,'gr','rtl',null,'N','5','RECURSO','Coluna usada para o nome');
Insert into DWU.BI_OBJECT_PADRAO values ('GEOMAPA','LAT','TEXTO','Coluna da latitude',null,'gr','rtl',null,'N','5','RECURSO','Coluna usada para a latitude');
Insert into DWU.BI_OBJECT_PADRAO values ('GEOMAPA','LON','TEXTO','Colun da longitude',null,'gr','rtl',null,'N','5','RECURSO','Coluna usada para a longitude');
Insert into DWU.BI_OBJECT_PADRAO values ('GEOMAPA','INFO','TEXTO','Colun da informação',null,'gr','rtl',null,'N','5','RECURSO','Coluna usada para a informação adicional');
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FUNDO_TIT','COR_GOM','Fundo título','#DDDDDD','gr','bgcolor',null,'N','6','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FONTE_TIT','COR_GOM','Cor/Fonte título','#000000','gr','color',null,'N','7','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','HIDDEN','CHECK_ONLY','Esconder valores','1','gr','rtl','$opc|1|Não|0|Sim','N','0','RECURSO','Esconder valores do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('PONTEIRO','DASH_MARGIN_TOP','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','LARGURA','INTEIRO','Largura','600','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','ALTURA','INTEIRO','Altura','400','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','TIT_COLOR','COR_FONTE','Cor/Fonte Título','#000000','ds','color',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','TIT_BGCOLOR','COR_FUNDO','Cor/Fundo Título','#999999','ds','bgcolor',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','TIT_IT','ITALICO','Título Itálico','normal','ds','fontStyle',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','TIT_BOLD','NEGRITO','Título Negrito','bold','ds','fontWeight',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','TIT_FONT','FONTE','Fonte Título','Arial','ds','fontFamily',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','TIT_SIZE','LOCAL','Tamanho Título','18px','ds','fontSize','$opc|18px|normal|12px|12|14px|14|16px|16|22px|22|28px|28|36px|36|48px|48|72px|72|90px|90','N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','MAX','CHECK_ONLY','Usar maior valor','N','gr','rtl','$opc|N|Não|S|Sim','N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','COR_LINHA','COR_GOM','Cor Linha','#FF0000','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','BGCOLOR','COR_GOM','Cor de fundo','#FFFFFF','gr','bgcolor',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','BGCOLOR','COR_GOM','Cor de fundo','#FFFFFF','gr','bgcolor',null,'N',null,'VISUAL','Cor do fundo do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','LARGURA','INTEIRO','Largura','800','gr','rtl',null,'N',null,'VISUAL','Largura do gráfico');
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','LARGURA','INTEIRO','Largura','800','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','ALTURA','INTEIRO','Altura','320','gr','rtl',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','NO_TUP','CHECK_ONLY','Sem Total Pivot','N','gr','rtl',null,'N',null,'RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FONTE_TOTAL','COR_GOM','Cor/Fonte total','#000000','gr','color',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FONTE_CABECALHO','COR_GOM','Cor/Fonte cabecalho','#000000','gr','color',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FUNDO_CABECALHO','COR_GOM','Fundo cabecalho','#999999','gr','bgcolor',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','DASH_MARGIN_TOP','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FUNDO_TOTAL','COR_GOM','Fundo total','#999999','gr','bgcolor',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FONTE_CLARO','COR_GOM','Cor/Fonte linha-clara','#000000','gr','color',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FONTE_ESCURO','COR_GOM','Cor/Fonte linha-escura','#000000','gr','color',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FUNDO_CLARO','COR_GOM','Fundo claro','#FFFFFF','gr','bgcolor',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FUNDO_ESCURO','COR_GOM','Fundo escuro','#CCCCCC','gr','bgcolor',null,'N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','DEGRADE','DEGRADE','Dêgrade','N','gr','rtl',null,'N','1','VISUAL','Degrade entre a cor do fundo do objeto e do fundo do titulo');
Insert into DWU.BI_OBJECT_PADRAO values ('SCRIPT','BGCOLOR','COR_FUNDO','Cor de fundo','#FFFFFF','ds','bgcolor',null,'N','4','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('SCRIPT','IT','ITALICO','Bloco em itálico',null,null,null,null,'N','7','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('SCRIPT','BOLD','NEGRITO','Bloco em negrito',null,'ds','fontWeight',null,'N','9','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('SCRIPT','FONT','FONTE','Fonte do bloco','Courier New','ds','fontFamily',null,'N','6','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('SCRIPT','COLOR','COR_FONTE','Cor da fonte','#000000','ds','color',null,'N','8','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('SCRIPT','EM_ESPERA','TEXTO','Conflitos',null,'gr','fil',null,'N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','TIT_COLOR','COR_FONTE','Cor/Fonte Título','#000000','ds','color',null,'N',null,'VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('VALOR','DASH_MARGIN_TOP','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('CONSULTA','FIXAR_TOT','CHECK_ONLY','Fixar total','N','gr','rtl',null,'S','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','TEXTO_ACUMULADO','TEXTO','Resto da amostra',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','TEXTO_ACUMULADO','TEXTO','Resto da amostra',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','TEXTO_ACUMULADO','TEXTO','Resto da amostra',null,'gr','rtl',null,'N','0','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('FLOAT_FILTER','FORMATO','LOCAL','Formato','0','gr','rtl','$opc|0|Código e descrição|1|Somente código|2|Somente descrição','N','5','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','FRACAO','LOCAL','Percentual','N','gr','rtl','$opc|A|Ambos|N|Não|S|Sim','N','1','RECURSO',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS','DASH_MARGIN_TOP','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('PIZZA','DASH_MARGIN_TOP','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS','DASH_MARGIN_TOP','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('MAPA','DASH_MARGIN_TOP','INTEIRO','Espaço no dashboard','4px','gr','rtl',null,'N','0','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS','XPOS' ,'LOCAL','Posição label do eixo-x','end','gr','rtl','$opc|middle|meio|end|fim','N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS' ,'XPOS' ,'LOCAL','Posição label do eixo-x','end','gr','rtl','$opc|middle|meio|end|fim','N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('LINHAS' ,'XPOS' ,'LOCAL','Posição label do eixo-x','end','gr','rtl','$opc|middle|meio|end|fim','N','1','VISUAL',null);
--
Insert into DWU.BI_OBJECT_PADRAO values ('BARRAS',  'POSICAO' ,'LOCAL','Posição do valor','inside','gr','rtl','$opc|inside|dentro|right|direita|insideRight|dentro-direita|insideLeft|dentro-esquerda','N','1','VISUAL',null);
Insert into DWU.BI_OBJECT_PADRAO values ('COLUNAS' ,'POSICAO' ,'LOCAL','Posição do valor','top',   'gr','rtl','$opc|top|cima|inside|dentro|insideTop|dentro-cima|insideBottom|dentro-baixo','N','1','VISUAL',null);
--
COMMIT; 
--
END;
